var annotated_dup =
[
    [ "pfc", "namespacepfc.html", [
      [ "algorithms", "namespacepfc_1_1algorithms.html", [
        [ "CodecSelector", "structpfc_1_1algorithms_1_1CodecSelector.html", "structpfc_1_1algorithms_1_1CodecSelector" ],
        [ "CompressionStats", "structpfc_1_1algorithms_1_1CompressionStats.html", "structpfc_1_1algorithms_1_1CompressionStats" ],
        [ "DeltaCodec", "classpfc_1_1algorithms_1_1DeltaCodec.html", "classpfc_1_1algorithms_1_1DeltaCodec" ],
        [ "PackedStream", "classpfc_1_1algorithms_1_1PackedStream.html", "classpfc_1_1algorithms_1_1PackedStream" ],
        [ "ParallelEncoder", "structpfc_1_1algorithms_1_1ParallelEncoder.html", "structpfc_1_1algorithms_1_1ParallelEncoder" ],
        [ "RunLengthCodec", "classpfc_1_1algorithms_1_1RunLengthCodec.html", "classpfc_1_1algorithms_1_1RunLengthCodec" ]
      ] ],
      [ "codecs", "namespacepfc_1_1codecs.html", [
        [ "Adaptive", "structpfc_1_1codecs_1_1Adaptive.html", "structpfc_1_1codecs_1_1Adaptive" ],
        [ "AdaptiveHuffman", "classpfc_1_1codecs_1_1AdaptiveHuffman.html", "classpfc_1_1codecs_1_1AdaptiveHuffman" ],
        [ "Boolean", "structpfc_1_1codecs_1_1Boolean.html", "structpfc_1_1codecs_1_1Boolean" ],
        [ "CanonicalHuffman", "classpfc_1_1codecs_1_1CanonicalHuffman.html", "classpfc_1_1codecs_1_1CanonicalHuffman" ],
        [ "Complex", "structpfc_1_1codecs_1_1Complex.html", "structpfc_1_1codecs_1_1Complex" ],
        [ "EliasDelta", "structpfc_1_1codecs_1_1EliasDelta.html", "structpfc_1_1codecs_1_1EliasDelta" ],
        [ "EliasGamma", "structpfc_1_1codecs_1_1EliasGamma.html", "structpfc_1_1codecs_1_1EliasGamma" ],
        [ "EliasOmega", "structpfc_1_1codecs_1_1EliasOmega.html", "structpfc_1_1codecs_1_1EliasOmega" ],
        [ "ExpGolomb", "structpfc_1_1codecs_1_1ExpGolomb.html", "structpfc_1_1codecs_1_1ExpGolomb" ],
        [ "Fibonacci", "structpfc_1_1codecs_1_1Fibonacci.html", "structpfc_1_1codecs_1_1Fibonacci" ],
        [ "Fixed", "structpfc_1_1codecs_1_1Fixed.html", "structpfc_1_1codecs_1_1Fixed" ],
        [ "FixedDecimal", "structpfc_1_1codecs_1_1FixedDecimal.html", "structpfc_1_1codecs_1_1FixedDecimal" ],
        [ "FloatingPoint", "structpfc_1_1codecs_1_1FloatingPoint.html", "structpfc_1_1codecs_1_1FloatingPoint" ],
        [ "HuffmanNode", "structpfc_1_1codecs_1_1HuffmanNode.html", "structpfc_1_1codecs_1_1HuffmanNode" ],
        [ "Interval", "structpfc_1_1codecs_1_1Interval.html", "structpfc_1_1codecs_1_1Interval" ],
        [ "Rational", "structpfc_1_1codecs_1_1Rational.html", "structpfc_1_1codecs_1_1Rational" ],
        [ "Rice", "structpfc_1_1codecs_1_1Rice.html", "structpfc_1_1codecs_1_1Rice" ],
        [ "Scientific", "structpfc_1_1codecs_1_1Scientific.html", "structpfc_1_1codecs_1_1Scientific" ],
        [ "Signed", "structpfc_1_1codecs_1_1Signed.html", "structpfc_1_1codecs_1_1Signed" ],
        [ "StaticHuffman", "classpfc_1_1codecs_1_1StaticHuffman.html", "classpfc_1_1codecs_1_1StaticHuffman" ],
        [ "Unary", "structpfc_1_1codecs_1_1Unary.html", "structpfc_1_1codecs_1_1Unary" ],
        [ "VByte", "structpfc_1_1codecs_1_1VByte.html", "structpfc_1_1codecs_1_1VByte" ]
      ] ],
      [ "compression", "namespacepfc_1_1compression.html", [
        [ "LZ77Compressor", "classpfc_1_1compression_1_1LZ77Compressor.html", "classpfc_1_1compression_1_1LZ77Compressor" ],
        [ "LZ77Config", "structpfc_1_1compression_1_1LZ77Config.html", "structpfc_1_1compression_1_1LZ77Config" ],
        [ "LZ77Decompressor", "classpfc_1_1compression_1_1LZ77Decompressor.html", "classpfc_1_1compression_1_1LZ77Decompressor" ],
        [ "LZ77Match", "structpfc_1_1compression_1_1LZ77Match.html", "structpfc_1_1compression_1_1LZ77Match" ],
        [ "LZSS", "classpfc_1_1compression_1_1LZSS.html", "classpfc_1_1compression_1_1LZSS" ]
      ] ],
      [ "integrity", "namespacepfc_1_1integrity.html", [
        [ "Adler32", "classpfc_1_1integrity_1_1Adler32.html", "classpfc_1_1integrity_1_1Adler32" ],
        [ "ChecksummedData", "classpfc_1_1integrity_1_1ChecksummedData.html", "classpfc_1_1integrity_1_1ChecksummedData" ],
        [ "CRC16", "classpfc_1_1integrity_1_1CRC16.html", "classpfc_1_1integrity_1_1CRC16" ],
        [ "CRC32", "classpfc_1_1integrity_1_1CRC32.html", "classpfc_1_1integrity_1_1CRC32" ],
        [ "CRC64", "classpfc_1_1integrity_1_1CRC64.html", "classpfc_1_1integrity_1_1CRC64" ],
        [ "XXHash32", "classpfc_1_1integrity_1_1XXHash32.html", "classpfc_1_1integrity_1_1XXHash32" ]
      ] ],
      [ "succinct", "namespacepfc_1_1succinct.html", [
        [ "BlockRankSupport", "classpfc_1_1succinct_1_1BlockRankSupport.html", "classpfc_1_1succinct_1_1BlockRankSupport" ],
        [ "SuccinctBitVector", "classpfc_1_1succinct_1_1SuccinctBitVector.html", "classpfc_1_1succinct_1_1SuccinctBitVector" ]
      ] ],
      [ "adaptive_probability_model", "classpfc_1_1adaptive__probability__model.html", "classpfc_1_1adaptive__probability__model" ],
      [ "arithmetic_decoder", "classpfc_1_1arithmetic__decoder.html", "classpfc_1_1arithmetic__decoder" ],
      [ "arithmetic_encoder", "classpfc_1_1arithmetic__encoder.html", "classpfc_1_1arithmetic__encoder" ],
      [ "ArithmeticCodec", "structpfc_1_1ArithmeticCodec.html", "structpfc_1_1ArithmeticCodec" ],
      [ "async_stream_reader", "classpfc_1_1async__stream__reader.html", null ],
      [ "async_stream_writer", "classpfc_1_1async__stream__writer.html", null ],
      [ "BasicBitReader", "classpfc_1_1BasicBitReader.html", "classpfc_1_1BasicBitReader" ],
      [ "BasicBitWriter", "classpfc_1_1BasicBitWriter.html", "classpfc_1_1BasicBitWriter" ],
      [ "BasicPackedBuffer", "classpfc_1_1BasicPackedBuffer.html", "classpfc_1_1BasicPackedBuffer" ],
      [ "BasicPackedVector", "classpfc_1_1BasicPackedVector.html", "classpfc_1_1BasicPackedVector" ],
      [ "bit_streambuf", "classpfc_1_1bit__streambuf.html", "classpfc_1_1bit__streambuf" ],
      [ "BitReader", "classpfc_1_1BitReader.html", "classpfc_1_1BitReader" ],
      [ "BitWriter", "classpfc_1_1BitWriter.html", "classpfc_1_1BitWriter" ],
      [ "Bottom", "classpfc_1_1Bottom.html", "classpfc_1_1Bottom" ],
      [ "buffer_size_manip", "structpfc_1_1buffer__size__manip.html", "structpfc_1_1buffer__size__manip" ],
      [ "codec_manip", "structpfc_1_1codec__manip.html", "structpfc_1_1codec__manip" ],
      [ "context_model", "classpfc_1_1context__model.html", "classpfc_1_1context__model" ],
      [ "DataValidator", "classpfc_1_1DataValidator.html", "classpfc_1_1DataValidator" ],
      [ "input_bit_streambuf", "classpfc_1_1input__bit__streambuf.html", "classpfc_1_1input__bit__streambuf" ],
      [ "OptimalCodec", "structpfc_1_1OptimalCodec.html", "structpfc_1_1OptimalCodec" ],
      [ "output_bit_streambuf", "classpfc_1_1output__bit__streambuf.html", "classpfc_1_1output__bit__streambuf" ],
      [ "Packed", "classpfc_1_1Packed.html", "classpfc_1_1Packed" ],
      [ "PackedAffineTransform", "classpfc_1_1PackedAffineTransform.html", "classpfc_1_1PackedAffineTransform" ],
      [ "PackedBuffer", "classpfc_1_1PackedBuffer.html", "classpfc_1_1PackedBuffer" ],
      [ "PackedContainer", "classpfc_1_1PackedContainer.html", "classpfc_1_1PackedContainer" ],
      [ "PackedIterator", "classpfc_1_1PackedIterator.html", "classpfc_1_1PackedIterator" ],
      [ "PackedList", "classpfc_1_1PackedList.html", "classpfc_1_1PackedList" ],
      [ "PackedMatrix", "classpfc_1_1PackedMatrix.html", "classpfc_1_1PackedMatrix" ],
      [ "PackedOptional", "classpfc_1_1PackedOptional.html", "classpfc_1_1PackedOptional" ],
      [ "PackedPair", "classpfc_1_1PackedPair.html", "classpfc_1_1PackedPair" ],
      [ "PackedPoint", "classpfc_1_1PackedPoint.html", "classpfc_1_1PackedPoint" ],
      [ "PackedProxy", "classpfc_1_1PackedProxy.html", "classpfc_1_1PackedProxy" ],
      [ "PackedSharedPtr", "classpfc_1_1PackedSharedPtr.html", "classpfc_1_1PackedSharedPtr" ],
      [ "PackedTree", "classpfc_1_1PackedTree.html", "classpfc_1_1PackedTree" ],
      [ "PackedTuple", "classpfc_1_1PackedTuple.html", "classpfc_1_1PackedTuple" ],
      [ "PackedVariant", "classpfc_1_1PackedVariant.html", "classpfc_1_1PackedVariant" ],
      [ "PackedVec", "classpfc_1_1PackedVec.html", "classpfc_1_1PackedVec" ],
      [ "PackedVector", "classpfc_1_1PackedVector.html", "classpfc_1_1PackedVector" ],
      [ "pfc_error_category", "classpfc_1_1pfc__error__category.html", "classpfc_1_1pfc__error__category" ],
      [ "range_decoder", "classpfc_1_1range__decoder.html", "classpfc_1_1range__decoder" ],
      [ "range_encoder", "classpfc_1_1range__encoder.html", "classpfc_1_1range__encoder" ],
      [ "RangeCodec", "structpfc_1_1RangeCodec.html", "structpfc_1_1RangeCodec" ],
      [ "result", "classpfc_1_1result.html", "classpfc_1_1result" ],
      [ "result< void >", "classpfc_1_1result_3_01void_01_4.html", "classpfc_1_1result_3_01void_01_4" ],
      [ "SafeBitReader", "classpfc_1_1SafeBitReader.html", "classpfc_1_1SafeBitReader" ],
      [ "SafeBitWriter", "classpfc_1_1SafeBitWriter.html", "classpfc_1_1SafeBitWriter" ],
      [ "static_probability_model", "classpfc_1_1static__probability__model.html", "classpfc_1_1static__probability__model" ],
      [ "stream_bit_reader", "classpfc_1_1stream__bit__reader.html", "classpfc_1_1stream__bit__reader" ],
      [ "stream_bit_writer", "classpfc_1_1stream__bit__writer.html", "classpfc_1_1stream__bit__writer" ],
      [ "TypeErasedPackedContainer", "classpfc_1_1TypeErasedPackedContainer.html", "classpfc_1_1TypeErasedPackedContainer" ],
      [ "Unit", "structpfc_1_1Unit.html", "structpfc_1_1Unit" ],
      [ "WriterTransaction", "classpfc_1_1WriterTransaction.html", "classpfc_1_1WriterTransaction" ]
    ] ],
    [ "std", "namespacestd.html", [
      [ "is_error_code_enum< pfc::pfc_error >", "structstd_1_1is__error__code__enum_3_01pfc_1_1pfc__error_01_4.html", null ],
      [ "tuple_size< pfc::succinct::SuccinctBitVector >", "structstd_1_1tuple__size_3_01pfc_1_1succinct_1_1SuccinctBitVector_01_4.html", null ]
    ] ]
];