PFC - Prefix-Free Codecs: pfc::codecs::CanonicalHuffman< Symbol > Class Template Reference
pfc::codecs::CanonicalHuffman< Symbol > Class Template Reference
#include <pfc/huffman.hpp>
Public Types
using symbol_type = Symbol
using frequency_map = std::unordered_map< Symbol, uint64_t >
Public Member Functions
template<typename BitSink >
result< void > encode_symbol (Symbol symbol, BitSink &sink) const
Static Public Member Functions
static result< CanonicalHuffman > from_frequencies (const frequency_map &frequencies)
Detailed Description
template<typename Symbol = uint8_t>
class pfc::codecs::CanonicalHuffman< Symbol >
Definition at line 282 of file huffman.hpp.
Member Typedef Documentation
frequency_map
template<typename Symbol = uint8_t> using pfc::codecs::CanonicalHuffman< Symbol >::frequency_map = std::unordered_map<Symbol, uint64_t>
Definition at line 285 of file huffman.hpp.
symbol_type
template<typename Symbol = uint8_t> using pfc::codecs::CanonicalHuffman< Symbol >::symbol_type = Symbol
Definition at line 284 of file huffman.hpp.
Member Function Documentation
encode_symbol()
template<typename Symbol = uint8_t> template<typename BitSink > result< void > pfc::codecs::CanonicalHuffman< Symbol >::encode_symbol (Symbol symbol, BitSink & sink) const inline
Definition at line 306 of file huffman.hpp.
References pfc::invalid_input, and pfc::make_error_code().
from_frequencies()
template<typename Symbol = uint8_t> static result< CanonicalHuffman > pfc::codecs::CanonicalHuffman< Symbol >::from_frequencies (const frequency_map & frequencies) inline static
Definition at line 287 of file huffman.hpp.
References pfc::codecs::StaticHuffman< Symbol, Allocator >::from_frequencies(), pfc::invalid_input, and pfc::make_error_code().
The documentation for this class was generated from the following file:
pfc/huffman.hpp