PFC - Prefix-Free Codecs: pfc::integrity::CRC32 Class Reference
pfc::integrity::CRC32 Class Reference
#include <pfc/crc.hpp>
Public Member Functions
CRC32 ()
void update (uint8_t byte)
void update (const uint8_t *data, size_t length)
void update (std::span< const uint8_t > data)
uint32_t finalize () const
void reset ()
Static Public Member Functions
static uint32_t calculate (const uint8_t *data, size_t length)
static uint32_t calculate (std::span< const uint8_t > data)
Static Public Attributes
static constexpr uint32_t polynomial = 0xEDB88320
static constexpr uint32_t initial_value = 0xFFFFFFFF
static constexpr uint32_t final_xor = 0xFFFFFFFF
Detailed Description
Definition at line 15 of file crc.hpp.
Constructor & Destructor Documentation
CRC32()
pfc::integrity::CRC32::CRC32 () inline
Definition at line 21 of file crc.hpp.
Member Function Documentation
calculate() [1/2]
static uint32_t pfc::integrity::CRC32::calculate (const uint8_t * data, size_t length) inline static
Definition at line 50 of file crc.hpp.
References finalize(), and update().
Referenced by calculate().
calculate() [2/2]
static uint32_t pfc::integrity::CRC32::calculate (std::span< const uint8_t > data) inline static
Definition at line 56 of file crc.hpp.
References calculate().
finalize()
uint32_t pfc::integrity::CRC32::finalize () const inline
Definition at line 41 of file crc.hpp.
References final_xor.
Referenced by calculate().
reset()
void pfc::integrity::CRC32::reset () inline
Definition at line 45 of file crc.hpp.
References initial_value.
update() [1/3]
void pfc::integrity::CRC32::update (const uint8_t * data, size_t length) inline
Definition at line 31 of file crc.hpp.
References update().
update() [2/3]
void pfc::integrity::CRC32::update (std::span< const uint8_t > data) inline
Definition at line 37 of file crc.hpp.
References update().
update() [3/3]
void pfc::integrity::CRC32::update (uint8_t byte) inline
Definition at line 27 of file crc.hpp.
Referenced by calculate(), update(), and update().
Member Data Documentation
final_xor
constexpr uint32_t pfc::integrity::CRC32::final_xor = 0xFFFFFFFF static constexpr
Definition at line 19 of file crc.hpp.
Referenced by finalize().
initial_value
constexpr uint32_t pfc::integrity::CRC32::initial_value = 0xFFFFFFFF static constexpr
Definition at line 18 of file crc.hpp.
Referenced by reset().
polynomial
constexpr uint32_t pfc::integrity::CRC32::polynomial = 0xEDB88320 static constexpr
Definition at line 17 of file crc.hpp.
The documentation for this class was generated from the following file:
pfc/crc.hpp