PFC - Prefix-Free Codecs: pfc::arithmetic_encoder Class Reference
pfc::arithmetic_encoder Class Reference
#include <pfc/arithmetic_coding.hpp>
Public Member Functions
arithmetic_encoder (BitWriter &sink)
template<ProbabilityModel Model>
void encode_symbol (std::size_t symbol, Model &model)
void finish ()
Detailed Description
Definition at line 206 of file arithmetic_coding.hpp.
Constructor & Destructor Documentation
arithmetic_encoder()
pfc::arithmetic_encoder::arithmetic_encoder (BitWriter & sink) inline explicit
Definition at line 226 of file arithmetic_coding.hpp.
Member Function Documentation
encode_symbol()
template<ProbabilityModel Model> void pfc::arithmetic_encoder::encode_symbol (std::size_t symbol, Model & model) inline
Definition at line 229 of file arithmetic_coding.hpp.
Referenced by pfc::arithmetic_compress(), and pfc::ArithmeticCodec< T, Symbols >::encode().
finish()
void pfc::arithmetic_encoder::finish () inline
Definition at line 277 of file arithmetic_coding.hpp.
Referenced by pfc::arithmetic_compress(), and pfc::ArithmeticCodec< T, Symbols >::encode().
The documentation for this class was generated from the following file:
pfc/arithmetic_coding.hpp