PFC - Prefix-Free Codecs: pfc::BasicBitReader< Allocator > Class Template Reference
pfc::BasicBitReader< Allocator > Class Template Reference
#include <pfc/allocator_support.hpp>
Public Types
using allocator_type = Allocator
Public Member Functions
BasicBitReader (const uint8_t *data, size_t size)
BasicBitReader (const std::vector< uint8_t, Allocator > &buffer)
bool read ()
bool read_bit ()
bool peek () const
uint64_t read_bits (int n)
void align ()
bool eof () const
size_t position () const
Detailed Description
template<typename Allocator = std::allocator<uint8_t>>
class pfc::BasicBitReader< Allocator >
Definition at line 83 of file allocator_support.hpp.
Member Typedef Documentation
allocator_type
template<typename Allocator = std::allocator<uint8_t>> using pfc::BasicBitReader< Allocator >::allocator_type = Allocator
Definition at line 85 of file allocator_support.hpp.
Constructor & Destructor Documentation
BasicBitReader() [1/2]
template<typename Allocator = std::allocator<uint8_t>> pfc::BasicBitReader< Allocator >::BasicBitReader (const uint8_t * data, size_t size) inline explicit
Definition at line 87 of file allocator_support.hpp.
BasicBitReader() [2/2]
template<typename Allocator = std::allocator<uint8_t>> pfc::BasicBitReader< Allocator >::BasicBitReader (const std::vector< uint8_t, Allocator > & buffer) inline
Definition at line 90 of file allocator_support.hpp.
Member Function Documentation
align()
template<typename Allocator = std::allocator<uint8_t>> void pfc::BasicBitReader< Allocator >::align () inline
Definition at line 118 of file allocator_support.hpp.
eof()
template<typename Allocator = std::allocator<uint8_t>> bool pfc::BasicBitReader< Allocator >::eof () const inline
Definition at line 122 of file allocator_support.hpp.
peek()
template<typename Allocator = std::allocator<uint8_t>> bool pfc::BasicBitReader< Allocator >::peek () const inline
Definition at line 106 of file allocator_support.hpp.
position()
template<typename Allocator = std::allocator<uint8_t>> size_t pfc::BasicBitReader< Allocator >::position () const inline
Definition at line 126 of file allocator_support.hpp.
Referenced by pfc::BasicPackedBuffer< Allocator >::unpack().
read()
template<typename Allocator = std::allocator<uint8_t>> bool pfc::BasicBitReader< Allocator >::read () inline
Definition at line 93 of file allocator_support.hpp.
Referenced by pfc::BasicBitReader< Allocator >::read_bit(), and pfc::BasicBitReader< Allocator >::read_bits().
read_bit()
template<typename Allocator = std::allocator<uint8_t>> bool pfc::BasicBitReader< Allocator >::read_bit () inline
Definition at line 102 of file allocator_support.hpp.
References pfc::BasicBitReader< Allocator >::read().
read_bits()
template<typename Allocator = std::allocator<uint8_t>> uint64_t pfc::BasicBitReader< Allocator >::read_bits (int n) inline
Definition at line 110 of file allocator_support.hpp.
References pfc::BasicBitReader< Allocator >::read().
The documentation for this class was generated from the following file:
pfc/allocator_support.hpp