PFC - Prefix-Free Codecs: pfc::compression::LZ77Decompressor< Allocator > Class Template Reference
pfc::compression::LZ77Decompressor< Allocator > Class Template Reference
#include <pfc/lz77.hpp>
Public Types
using allocator_type = Allocator
Public Member Functions
LZ77Decompressor (const Allocator &alloc=Allocator())
template<typename InputIt , typename OutputIt >
result< size_t > decompress (InputIt first, InputIt last, OutputIt output)
template<typename BitSource , typename OutputIt >
result< size_t > decompress_from_bits (BitSource &source, OutputIt output)
Detailed Description
template<typename Allocator = std::allocator<uint8_t>>
class pfc::compression::LZ77Decompressor< Allocator >
Definition at line 231 of file lz77.hpp.
Member Typedef Documentation
allocator_type
template<typename Allocator = std::allocator<uint8_t>> using pfc::compression::LZ77Decompressor< Allocator >::allocator_type = Allocator
Definition at line 233 of file lz77.hpp.
Constructor & Destructor Documentation
LZ77Decompressor()
template<typename Allocator = std::allocator<uint8_t>> pfc::compression::LZ77Decompressor< Allocator >::LZ77Decompressor (const Allocator & alloc = Allocator()) inline explicit
Definition at line 235 of file lz77.hpp.
Member Function Documentation
decompress()
template<typename Allocator = std::allocator<uint8_t>> template<typename InputIt , typename OutputIt > result< size_t > pfc::compression::LZ77Decompressor< Allocator >::decompress (InputIt first, InputIt last, OutputIt output) inline
Definition at line 242 of file lz77.hpp.
References pfc::corrupted_data, pfc::compression::LZ77Match::distance, pfc::compression::LZ77Match::is_literal(), pfc::compression::LZ77Match::length, pfc::compression::LZ77Match::literal, and pfc::make_error_code().
Referenced by pfc::compression::LZ77Decompressor< Allocator >::decompress_from_bits().
decompress_from_bits()
template<typename Allocator = std::allocator<uint8_t>> template<typename BitSource , typename OutputIt > result< size_t > pfc::compression::LZ77Decompressor< Allocator >::decompress_from_bits (BitSource & source, OutputIt output) inline
Definition at line 275 of file lz77.hpp.
References pfc::corrupted_data, pfc::compression::LZ77Match::decode(), pfc::compression::LZ77Decompressor< Allocator >::decompress(), pfc::incomplete_data, and pfc::make_error_code().
The documentation for this class was generated from the following file:
pfc/lz77.hpp