PFC - Prefix-Free Codecs: pfc::SafeBitReader< Allocator > Class Template Reference
pfc::SafeBitReader< Allocator > Class Template Reference
#include <pfc/error_handling.hpp>
Public Types
using allocator_type = Allocator
Public Member Functions
SafeBitReader (const uint8_t *data, size_t size)
SafeBitReader (const std::vector< uint8_t, Allocator > &buffer)
result< bool > read_bit ()
result< uint64_t > read_bits (int n)
void align ()
bool eof () const
size_t position () const
bool is_valid () const
Detailed Description
template<typename Allocator = std::allocator<uint8_t>>
class pfc::SafeBitReader< Allocator >
Definition at line 246 of file error_handling.hpp.
Member Typedef Documentation
allocator_type
template<typename Allocator = std::allocator<uint8_t>> using pfc::SafeBitReader< Allocator >::allocator_type = Allocator
Definition at line 248 of file error_handling.hpp.
Constructor & Destructor Documentation
SafeBitReader() [1/2]
template<typename Allocator = std::allocator<uint8_t>> pfc::SafeBitReader< Allocator >::SafeBitReader (const uint8_t * data, size_t size) inline
Definition at line 250 of file error_handling.hpp.
SafeBitReader() [2/2]
template<typename Allocator = std::allocator<uint8_t>> pfc::SafeBitReader< Allocator >::SafeBitReader (const std::vector< uint8_t, Allocator > & buffer) inline
Definition at line 257 of file error_handling.hpp.
Member Function Documentation
align()
template<typename Allocator = std::allocator<uint8_t>> void pfc::SafeBitReader< Allocator >::align () inline
Definition at line 291 of file error_handling.hpp.
eof()
template<typename Allocator = std::allocator<uint8_t>> bool pfc::SafeBitReader< Allocator >::eof () const inline
Definition at line 295 of file error_handling.hpp.
is_valid()
template<typename Allocator = std::allocator<uint8_t>> bool pfc::SafeBitReader< Allocator >::is_valid () const inline
Definition at line 303 of file error_handling.hpp.
position()
template<typename Allocator = std::allocator<uint8_t>> size_t pfc::SafeBitReader< Allocator >::position () const inline
Definition at line 299 of file error_handling.hpp.
read_bit()
template<typename Allocator = std::allocator<uint8_t>> result< bool > pfc::SafeBitReader< Allocator >::read_bit () inline
Definition at line 260 of file error_handling.hpp.
References pfc::eof_reached, pfc::invalid_input, and pfc::make_error_code().
Referenced by pfc::SafeBitReader< Allocator >::read_bits().
read_bits()
template<typename Allocator = std::allocator<uint8_t>> result< uint64_t > pfc::SafeBitReader< Allocator >::read_bits (int n) inline
Definition at line 275 of file error_handling.hpp.
References pfc::invalid_parameter, pfc::make_error_code(), and pfc::SafeBitReader< Allocator >::read_bit().
The documentation for this class was generated from the following file:
pfc/error_handling.hpp