PFC - Prefix-Free Codecs: pfc::PackedPoint< N, Coordinate > Class Template Reference
pfc::PackedPoint< N, Coordinate > Class Template Reference
#include <pfc/coordinates.hpp>
Public Types
using value_type = std::array< typename Coordinate::value_type, N >
using coordinate_type = Coordinate
Public Member Functions
PackedPoint ()=default
PackedPoint (const value_type &values)
template<typename... Args>
requires (sizeof...(Args) == N)
PackedPoint (Args... args)
const Coordinate & operator[] (size_t i) const
Coordinate & operator[] (size_t i)
value_type value () const
bool operator== (const PackedPoint &other) const
Static Public Member Functions
template<typename Sink >
requires BitSink<Sink>
static void encode (const PackedPoint &p, Sink &sink)
template<typename Source >
requires BitSource<Source>
static PackedPoint decode (Source &source)
Static Public Attributes
static constexpr size_t dimensions = N
Detailed Description
template<size_t N, PackedValue Coordinate = PackedU32<>>
class pfc::PackedPoint< N, Coordinate >
Definition at line 48 of file coordinates.hpp.
Member Typedef Documentation
coordinate_type
template<size_t N, PackedValue Coordinate = PackedU32<>> using pfc::PackedPoint< N, Coordinate >::coordinate_type = Coordinate
Definition at line 51 of file coordinates.hpp.
value_type
template<size_t N, PackedValue Coordinate = PackedU32<>> using pfc::PackedPoint< N, Coordinate >::value_type = std::array<typename Coordinate::value_type, N>
Definition at line 50 of file coordinates.hpp.
Constructor & Destructor Documentation
PackedPoint() [1/3]
template<size_t N, PackedValue Coordinate = PackedU32<>> pfc::PackedPoint< N, Coordinate >::PackedPoint () default
PackedPoint() [2/3]
template<size_t N, PackedValue Coordinate = PackedU32<>> pfc::PackedPoint< N, Coordinate >::PackedPoint (const value_type & values) inline explicit
Definition at line 61 of file coordinates.hpp.
PackedPoint() [3/3]
template<size_t N, PackedValue Coordinate = PackedU32<>> template<typename... Args> requires (sizeof...(Args) == N) pfc::PackedPoint< N, Coordinate >::PackedPoint (Args... args) inline explicit
Definition at line 68 of file coordinates.hpp.
Member Function Documentation
decode()
template<size_t N, PackedValue Coordinate = PackedU32<>> template<typename Source > requires BitSource<Source> static PackedPoint pfc::PackedPoint< N, Coordinate >::decode (Source & source) inline static
Definition at line 105 of file coordinates.hpp.
encode()
template<size_t N, PackedValue Coordinate = PackedU32<>> template<typename Sink > requires BitSink<Sink> static void pfc::PackedPoint< N, Coordinate >::encode (const PackedPoint< N, Coordinate > & p, Sink & sink) inline static
Definition at line 98 of file coordinates.hpp.
operator==()
template<size_t N, PackedValue Coordinate = PackedU32<>> bool pfc::PackedPoint< N, Coordinate >::operator== (const PackedPoint< N, Coordinate > & other) const inline
Definition at line 87 of file coordinates.hpp.
References pfc::PackedPoint< N, Coordinate >::value().
operator[]() [1/2]
template<size_t N, PackedValue Coordinate = PackedU32<>> Coordinate & pfc::PackedPoint< N, Coordinate >::operator[] (size_t i) inline
Definition at line 75 of file coordinates.hpp.
operator[]() [2/2]
template<size_t N, PackedValue Coordinate = PackedU32<>> const Coordinate & pfc::PackedPoint< N, Coordinate >::operator[] (size_t i) const inline
Definition at line 74 of file coordinates.hpp.
value()
template<size_t N, PackedValue Coordinate = PackedU32<>> value_type pfc::PackedPoint< N, Coordinate >::value () const inline
Definition at line 78 of file coordinates.hpp.
References pfc::result< T >::value().
Referenced by pfc::PackedPoint< N, Coordinate >::operator==().
Member Data Documentation
dimensions
template<size_t N, PackedValue Coordinate = PackedU32<>> constexpr size_t pfc::PackedPoint< N, Coordinate >::dimensions = N static constexpr
Definition at line 52 of file coordinates.hpp.
The documentation for this class was generated from the following file:
pfc/coordinates.hpp