PFC - Prefix-Free Codecs: pfc::BasicBitWriter< Allocator > Class Template Reference
pfc::BasicBitWriter< Allocator > Class Template Reference
#include <pfc/allocator_support.hpp>
Public Types
using allocator_type = Allocator
using byte_allocator = typename std::allocator_traits< Allocator >::template rebind_alloc< uint8_t >
using buffer_type = std::vector< uint8_t, byte_allocator >
Public Member Functions
BasicBitWriter (const Allocator &alloc=Allocator())
BasicBitWriter (size_t initial_capacity, const Allocator &alloc=Allocator())
void write (bool b)
void write_bit (bool b)
void write_bits (uint64_t v, int n)
void align ()
const buffer_type & buffer () const
buffer_type & buffer ()
size_t size () const
size_t bit_count () const
allocator_type get_allocator () const
Detailed Description
template<typename Allocator = std::allocator<uint8_t>>
class pfc::BasicBitWriter< Allocator >
Definition at line 16 of file allocator_support.hpp.
Member Typedef Documentation
allocator_type
template<typename Allocator = std::allocator<uint8_t>> using pfc::BasicBitWriter< Allocator >::allocator_type = Allocator
Definition at line 18 of file allocator_support.hpp.
buffer_type
template<typename Allocator = std::allocator<uint8_t>> using pfc::BasicBitWriter< Allocator >::buffer_type = std::vector<uint8_t, byte_allocator>
Definition at line 20 of file allocator_support.hpp.
byte_allocator
template<typename Allocator = std::allocator<uint8_t>> using pfc::BasicBitWriter< Allocator >::byte_allocator = typename std::allocator_traits<Allocator>::template rebind_alloc<uint8_t>
Definition at line 19 of file allocator_support.hpp.
Constructor & Destructor Documentation
BasicBitWriter() [1/2]
template<typename Allocator = std::allocator<uint8_t>> pfc::BasicBitWriter< Allocator >::BasicBitWriter (const Allocator & alloc = Allocator()) inline explicit
Definition at line 22 of file allocator_support.hpp.
BasicBitWriter() [2/2]
template<typename Allocator = std::allocator<uint8_t>> pfc::BasicBitWriter< Allocator >::BasicBitWriter (size_t initial_capacity, const Allocator & alloc = Allocator()) inline explicit
Definition at line 27 of file allocator_support.hpp.
Member Function Documentation
align()
template<typename Allocator = std::allocator<uint8_t>> void pfc::BasicBitWriter< Allocator >::align () inline
Definition at line 47 of file allocator_support.hpp.
Referenced by pfc::BasicPackedBuffer< Allocator >::pack().
bit_count()
template<typename Allocator = std::allocator<uint8_t>> size_t pfc::BasicBitWriter< Allocator >::bit_count () const inline
Definition at line 58 of file allocator_support.hpp.
buffer() [1/2]
template<typename Allocator = std::allocator<uint8_t>> buffer_type & pfc::BasicBitWriter< Allocator >::buffer () inline
Definition at line 52 of file allocator_support.hpp.
buffer() [2/2]
template<typename Allocator = std::allocator<uint8_t>> const buffer_type & pfc::BasicBitWriter< Allocator >::buffer () const inline
Definition at line 51 of file allocator_support.hpp.
Referenced by pfc::BasicPackedBuffer< Allocator >::pack().
get_allocator()
template<typename Allocator = std::allocator<uint8_t>> allocator_type pfc::BasicBitWriter< Allocator >::get_allocator () const inline
Definition at line 62 of file allocator_support.hpp.
size()
template<typename Allocator = std::allocator<uint8_t>> size_t pfc::BasicBitWriter< Allocator >::size () const inline
Definition at line 54 of file allocator_support.hpp.
write()
template<typename Allocator = std::allocator<uint8_t>> void pfc::BasicBitWriter< Allocator >::write (bool b) inline
Definition at line 32 of file allocator_support.hpp.
Referenced by pfc::BasicBitWriter< Allocator >::write_bit(), and pfc::BasicBitWriter< Allocator >::write_bits().
write_bit()
template<typename Allocator = std::allocator<uint8_t>> void pfc::BasicBitWriter< Allocator >::write_bit (bool b) inline
Definition at line 37 of file allocator_support.hpp.
References pfc::BasicBitWriter< Allocator >::write().
write_bits()
template<typename Allocator = std::allocator<uint8_t>> void pfc::BasicBitWriter< Allocator >::write_bits (uint64_t v, int n) inline
Definition at line 41 of file allocator_support.hpp.
References pfc::BasicBitWriter< Allocator >::write().
The documentation for this class was generated from the following file:
pfc/allocator_support.hpp