PFC - Prefix-Free Codecs: pfc::BitWriter Class Reference
pfc::BitWriter Class Reference
#include <pfc/core.hpp>
Public Member Functions
BitWriter (uint8_t *ptr) noexcept
BitWriter (std::span< uint8_t > buffer) noexcept
void write (bool bit) noexcept
void write_bits (uint64_t bits, size_t count) noexcept
void align () noexcept
size_t bytes_written () const noexcept
uint8_t * position () const noexcept
uint8_t * start () const noexcept
Detailed Description
Definition at line 54 of file core.hpp.
Constructor & Destructor Documentation
BitWriter() [1/2]
pfc::BitWriter::BitWriter (uint8_t * ptr) inline explicit noexcept
Definition at line 61 of file core.hpp.
BitWriter() [2/2]
pfc::BitWriter::BitWriter (std::span< uint8_t > buffer) inline explicit noexcept
Definition at line 62 of file core.hpp.
Member Function Documentation
align()
void pfc::BitWriter::align () inline noexcept
Definition at line 81 of file core.hpp.
Referenced by pfc::algorithms::analyze_compression(), pfc::arithmetic_compress(), pfc::algorithms::ParallelEncoder< T, Codec >::encode(), pfc::PackedContainer< Element >::push_back(), and pfc::range_compress().
bytes_written()
size_t pfc::BitWriter::bytes_written () const inline noexcept
Definition at line 90 of file core.hpp.
Referenced by pfc::arithmetic_compress(), pfc::PackedBuffer::operator<<(), pfc::PackedContainer< Element >::push_back(), and pfc::range_compress().
position()
uint8_t * pfc::BitWriter::position () const inline noexcept
Definition at line 95 of file core.hpp.
Referenced by pfc::algorithms::analyze_compression(), pfc::algorithms::ParallelEncoder< T, Codec >::encode(), and pfc::PackedBuffer::operator<<().
start()
uint8_t * pfc::BitWriter::start () const inline noexcept
Definition at line 100 of file core.hpp.
write()
void pfc::BitWriter::write (bool bit) inline noexcept
Definition at line 64 of file core.hpp.
Referenced by write_bits().
write_bits()
void pfc::BitWriter::write_bits (uint64_t bits, size_t count) inline noexcept
Definition at line 74 of file core.hpp.
References write().
Referenced by pfc::range_encoder::finish().
The documentation for this class was generated from the following file:
pfc/core.hpp