PFC - Prefix-Free Codecs: pfc::PackedList< Element > Class Template Reference
pfc::PackedList< Element > Class Template Reference
#include <pfc/algebraic.hpp>
Public Types
using value_type = std::vector< typename Element::value_type >
using element_type = Element
Public Member Functions
PackedList ()
PackedList (const Element &head, std::shared_ptr< PackedList > tail)
PackedList (const value_type &vec)
bool empty () const noexcept
const Element * head () const
std::shared_ptr< PackedList > tail () const
value_type value () const
template<typename F >
auto map (F &&f) const
template<typename F >
void for_each (F &&f) const
Static Public Member Functions
template<typename Sink >
requires BitSink<Sink>
static void encode (const PackedList &list, Sink &sink)
template<typename Source >
requires BitSource<Source>
static PackedList decode (Source &source)
Detailed Description
template<PackedValue Element>
class pfc::PackedList< Element >
Definition at line 269 of file algebraic.hpp.
Member Typedef Documentation
element_type
template<PackedValue Element> using pfc::PackedList< Element >::element_type = Element
Definition at line 272 of file algebraic.hpp.
value_type
template<PackedValue Element> using pfc::PackedList< Element >::value_type = std::vector<typename Element::value_type>
Definition at line 271 of file algebraic.hpp.
Constructor & Destructor Documentation
PackedList() [1/3]
template<PackedValue Element> pfc::PackedList< Element >::PackedList () inline
Definition at line 279 of file algebraic.hpp.
PackedList() [2/3]
template<PackedValue Element> pfc::PackedList< Element >::PackedList (const Element & head, std::shared_ptr< PackedList< Element > > tail) inline
Definition at line 281 of file algebraic.hpp.
References pfc::PackedList< Element >::head(), and pfc::PackedList< Element >::tail().
PackedList() [3/3]
template<PackedValue Element> pfc::PackedList< Element >::PackedList (const value_type & vec) inline explicit
Definition at line 286 of file algebraic.hpp.
References pfc::PackedList< Element >::tail().
Member Function Documentation
decode()
template<PackedValue Element> template<typename Source > requires BitSource<Source> static PackedList pfc::PackedList< Element >::decode (Source & source) inline static
Definition at line 376 of file algebraic.hpp.
References pfc::PackedVariant< Types >::decode().
empty()
template<PackedValue Element> bool pfc::PackedList< Element >::empty () const inline noexcept
Definition at line 307 of file algebraic.hpp.
References pfc::PackedVariant< Types >::index().
Referenced by pfc::PackedList< Element >::for_each(), pfc::PackedList< Element >::map(), and pfc::PackedList< Element >::value().
encode()
template<PackedValue Element> template<typename Sink > requires BitSink<Sink> static void pfc::PackedList< Element >::encode (const PackedList< Element > & list, Sink & sink) inline static
Definition at line 371 of file algebraic.hpp.
References pfc::PackedVariant< Types >::encode().
for_each()
template<PackedValue Element> template<typename F > void pfc::PackedList< Element >::for_each (F && f) const inline
Definition at line 360 of file algebraic.hpp.
References pfc::PackedList< Element >::empty(), pfc::PackedList< Element >::head(), and pfc::PackedList< Element >::tail().
head()
template<PackedValue Element> const Element * pfc::PackedList< Element >::head () const inline
Definition at line 311 of file algebraic.hpp.
Referenced by pfc::PackedList< Element >::for_each(), pfc::PackedList< Element >::map(), pfc::PackedList< Element >::PackedList(), and pfc::PackedList< Element >::value().
map()
template<PackedValue Element> template<typename F > auto pfc::PackedList< Element >::map (F && f) const inline
Definition at line 346 of file algebraic.hpp.
References pfc::PackedList< Element >::empty(), pfc::PackedList< Element >::head(), pfc::PackedList< Element >::map(), pfc::PackedList< Element >::tail(), and pfc::PackedList< Element >::value().
Referenced by pfc::PackedList< Element >::map().
tail()
template<PackedValue Element> std::shared_ptr< PackedList > pfc::PackedList< Element >::tail () const inline
Definition at line 318 of file algebraic.hpp.
Referenced by pfc::PackedList< Element >::for_each(), pfc::PackedList< Element >::map(), pfc::PackedList< Element >::PackedList(), pfc::PackedList< Element >::PackedList(), and pfc::PackedList< Element >::value().
value()
template<PackedValue Element> value_type pfc::PackedList< Element >::value () const inline
Definition at line 326 of file algebraic.hpp.
References pfc::PackedList< Element >::empty(), pfc::PackedList< Element >::head(), and pfc::PackedList< Element >::tail().
Referenced by pfc::PackedList< Element >::map().
The documentation for this class was generated from the following file:
pfc/algebraic.hpp