PFC - Prefix-Free Codecs: pfc::PackedTree< Value > Class Template Reference
pfc::PackedTree< Value > Class Template Reference
#include <pfc/algebraic.hpp>
Public Types
using value_type = Value
Public Member Functions
PackedTree ()
PackedTree (const Value &val, std::shared_ptr< PackedTree > left, std::shared_ptr< PackedTree > right)
bool empty () const noexcept
const Value * value () const
std::shared_ptr< PackedTree > left () const
std::shared_ptr< PackedTree > right () const
template<typename F >
void inorder (F &&f) const
template<typename F >
void preorder (F &&f) const
Static Public Member Functions
template<typename Sink >
requires BitSink<Sink>
static void encode (const PackedTree &tree, Sink &sink)
template<typename Source >
requires BitSource<Source>
static PackedTree decode (Source &source)
Detailed Description
template<PackedValue Value>
class pfc::PackedTree< Value >
Definition at line 399 of file algebraic.hpp.
Member Typedef Documentation
value_type
template<PackedValue Value> using pfc::PackedTree< Value >::value_type = Value
Definition at line 401 of file algebraic.hpp.
Constructor & Destructor Documentation
PackedTree() [1/2]
template<PackedValue Value> pfc::PackedTree< Value >::PackedTree () inline
Definition at line 408 of file algebraic.hpp.
PackedTree() [2/2]
template<PackedValue Value> pfc::PackedTree< Value >::PackedTree (const Value & val, std::shared_ptr< PackedTree< Value > > left, std::shared_ptr< PackedTree< Value > > right) inline
Definition at line 410 of file algebraic.hpp.
References pfc::PackedTree< Value >::left(), and pfc::PackedTree< Value >::right().
Member Function Documentation
decode()
template<PackedValue Value> template<typename Source > requires BitSource<Source> static PackedTree pfc::PackedTree< Value >::decode (Source & source) inline static
Definition at line 482 of file algebraic.hpp.
References pfc::PackedVariant< Types >::decode().
empty()
template<PackedValue Value> bool pfc::PackedTree< Value >::empty () const inline noexcept
Definition at line 422 of file algebraic.hpp.
References pfc::PackedVariant< Types >::index().
Referenced by pfc::PackedTree< Value >::inorder(), and pfc::PackedTree< Value >::preorder().
encode()
template<PackedValue Value> template<typename Sink > requires BitSink<Sink> static void pfc::PackedTree< Value >::encode (const PackedTree< Value > & tree, Sink & sink) inline static
Definition at line 477 of file algebraic.hpp.
References pfc::PackedVariant< Types >::encode().
inorder()
template<PackedValue Value> template<typename F > void pfc::PackedTree< Value >::inorder (F && f) const inline
Definition at line 458 of file algebraic.hpp.
References pfc::PackedTree< Value >::empty(), pfc::PackedTree< Value >::left(), pfc::PackedTree< Value >::right(), and pfc::PackedTree< Value >::value().
left()
template<PackedValue Value> std::shared_ptr< PackedTree > pfc::PackedTree< Value >::left () const inline
Definition at line 436 of file algebraic.hpp.
References pfc::PackedSharedPtr< T >::value().
Referenced by pfc::PackedTree< Value >::inorder(), pfc::PackedTree< Value >::PackedTree(), and pfc::PackedTree< Value >::preorder().
preorder()
template<PackedValue Value> template<typename F > void pfc::PackedTree< Value >::preorder (F && f) const inline
Definition at line 467 of file algebraic.hpp.
References pfc::PackedTree< Value >::empty(), pfc::PackedTree< Value >::left(), pfc::PackedTree< Value >::right(), and pfc::PackedTree< Value >::value().
right()
template<PackedValue Value> std::shared_ptr< PackedTree > pfc::PackedTree< Value >::right () const inline
Definition at line 446 of file algebraic.hpp.
References pfc::PackedSharedPtr< T >::value().
Referenced by pfc::PackedTree< Value >::inorder(), pfc::PackedTree< Value >::PackedTree(), and pfc::PackedTree< Value >::preorder().
value()
template<PackedValue Value> const Value * pfc::PackedTree< Value >::value () const inline
Definition at line 426 of file algebraic.hpp.
Referenced by pfc::PackedTree< Value >::inorder(), and pfc::PackedTree< Value >::preorder().
The documentation for this class was generated from the following file:
pfc/algebraic.hpp