PFC - Prefix-Free Codecs: pfc::integrity::CRC16 Class Reference
pfc::integrity::CRC16 Class Reference
#include <pfc/crc.hpp>
Public Member Functions
CRC16 ()
void update (uint8_t byte)
void update (const uint8_t *data, size_t length)
uint16_t finalize () const
void reset ()
Static Public Member Functions
static uint16_t calculate (const uint8_t *data, size_t length)
Static Public Attributes
static constexpr uint16_t polynomial = 0xA001
static constexpr uint16_t initial_value = 0x0000
static constexpr uint16_t final_xor = 0x0000
Detailed Description
Definition at line 154 of file crc.hpp.
Constructor & Destructor Documentation
CRC16()
pfc::integrity::CRC16::CRC16 () inline
Definition at line 160 of file crc.hpp.
Member Function Documentation
calculate()
static uint16_t pfc::integrity::CRC16::calculate (const uint8_t * data, size_t length) inline static
Definition at line 184 of file crc.hpp.
References finalize(), and update().
finalize()
uint16_t pfc::integrity::CRC16::finalize () const inline
Definition at line 176 of file crc.hpp.
References final_xor.
Referenced by calculate().
reset()
void pfc::integrity::CRC16::reset () inline
Definition at line 180 of file crc.hpp.
References initial_value.
update() [1/2]
void pfc::integrity::CRC16::update (const uint8_t * data, size_t length) inline
Definition at line 170 of file crc.hpp.
References update().
update() [2/2]
void pfc::integrity::CRC16::update (uint8_t byte) inline
Definition at line 166 of file crc.hpp.
Referenced by calculate(), and update().
Member Data Documentation
final_xor
constexpr uint16_t pfc::integrity::CRC16::final_xor = 0x0000 static constexpr
Definition at line 158 of file crc.hpp.
Referenced by finalize().
initial_value
constexpr uint16_t pfc::integrity::CRC16::initial_value = 0x0000 static constexpr
Definition at line 157 of file crc.hpp.
Referenced by reset().
polynomial
constexpr uint16_t pfc::integrity::CRC16::polynomial = 0xA001 static constexpr
Definition at line 156 of file crc.hpp.
The documentation for this class was generated from the following file:
pfc/crc.hpp