PFC - Prefix-Free Codecs: pfc::integrity::CRC64 Class Reference
pfc::integrity::CRC64 Class Reference
#include <pfc/crc.hpp>
Public Member Functions
CRC64 ()
void update (uint8_t byte)
void update (const uint8_t *data, size_t length)
void update (std::span< const uint8_t > data)
uint64_t finalize () const
void reset ()
Static Public Member Functions
static uint64_t calculate (const uint8_t *data, size_t length)
static uint64_t calculate (std::span< const uint8_t > data)
Static Public Attributes
static constexpr uint64_t polynomial = 0xC96C5795D7870F42ULL
static constexpr uint64_t initial_value = 0xFFFFFFFFFFFFFFFFULL
static constexpr uint64_t final_xor = 0xFFFFFFFFFFFFFFFFULL
Detailed Description
Definition at line 85 of file crc.hpp.
Constructor & Destructor Documentation
CRC64()
pfc::integrity::CRC64::CRC64 () inline
Definition at line 91 of file crc.hpp.
Member Function Documentation
calculate() [1/2]
static uint64_t pfc::integrity::CRC64::calculate (const uint8_t * data, size_t length) inline static
Definition at line 119 of file crc.hpp.
References finalize(), and update().
Referenced by calculate().
calculate() [2/2]
static uint64_t pfc::integrity::CRC64::calculate (std::span< const uint8_t > data) inline static
Definition at line 125 of file crc.hpp.
References calculate().
finalize()
uint64_t pfc::integrity::CRC64::finalize () const inline
Definition at line 111 of file crc.hpp.
References final_xor.
Referenced by calculate().
reset()
void pfc::integrity::CRC64::reset () inline
Definition at line 115 of file crc.hpp.
References initial_value.
update() [1/3]
void pfc::integrity::CRC64::update (const uint8_t * data, size_t length) inline
Definition at line 101 of file crc.hpp.
References update().
update() [2/3]
void pfc::integrity::CRC64::update (std::span< const uint8_t > data) inline
Definition at line 107 of file crc.hpp.
References update().
update() [3/3]
void pfc::integrity::CRC64::update (uint8_t byte) inline
Definition at line 97 of file crc.hpp.
Referenced by calculate(), update(), and update().
Member Data Documentation
final_xor
constexpr uint64_t pfc::integrity::CRC64::final_xor = 0xFFFFFFFFFFFFFFFFULL static constexpr
Definition at line 89 of file crc.hpp.
Referenced by finalize().
initial_value
constexpr uint64_t pfc::integrity::CRC64::initial_value = 0xFFFFFFFFFFFFFFFFULL static constexpr
Definition at line 88 of file crc.hpp.
Referenced by reset().
polynomial
constexpr uint64_t pfc::integrity::CRC64::polynomial = 0xC96C5795D7870F42ULL static constexpr
Definition at line 87 of file crc.hpp.
The documentation for this class was generated from the following file:
pfc/crc.hpp