PFC - Prefix-Free Codecs: pfc::integrity::XXHash32 Class Reference
pfc::integrity::XXHash32 Class Reference
#include <pfc/crc.hpp>
Public Member Functions
XXHash32 (uint32_t seed=0)
void update (const uint8_t *data, size_t length)
uint32_t finalize () const
void reset ()
Static Public Member Functions
static uint32_t calculate (const uint8_t *data, size_t length, uint32_t seed=0)
Static Public Attributes
static constexpr uint32_t prime1 = 0x9E3779B1U
static constexpr uint32_t prime2 = 0x85EBCA77U
static constexpr uint32_t prime3 = 0xC2B2AE3DU
static constexpr uint32_t prime4 = 0x27D4EB2FU
static constexpr uint32_t prime5 = 0x165667B1U
Detailed Description
Definition at line 264 of file crc.hpp.
Constructor & Destructor Documentation
XXHash32()
pfc::integrity::XXHash32::XXHash32 (uint32_t seed = 0) inline explicit
Definition at line 272 of file crc.hpp.
References reset().
Member Function Documentation
calculate()
static uint32_t pfc::integrity::XXHash32::calculate (const uint8_t * data, size_t length, uint32_t seed = 0) inline static
Definition at line 280 of file crc.hpp.
References finalize(), and update().
finalize()
uint32_t pfc::integrity::XXHash32::finalize () const
Referenced by calculate().
reset()
void pfc::integrity::XXHash32::reset ()
Referenced by XXHash32().
update()
void pfc::integrity::XXHash32::update (const uint8_t * data, size_t length)
Referenced by calculate().
Member Data Documentation
prime1
constexpr uint32_t pfc::integrity::XXHash32::prime1 = 0x9E3779B1U static constexpr
Definition at line 266 of file crc.hpp.
prime2
constexpr uint32_t pfc::integrity::XXHash32::prime2 = 0x85EBCA77U static constexpr
Definition at line 267 of file crc.hpp.
prime3
constexpr uint32_t pfc::integrity::XXHash32::prime3 = 0xC2B2AE3DU static constexpr
Definition at line 268 of file crc.hpp.
prime4
constexpr uint32_t pfc::integrity::XXHash32::prime4 = 0x27D4EB2FU static constexpr
Definition at line 269 of file crc.hpp.
prime5
constexpr uint32_t pfc::integrity::XXHash32::prime5 = 0x165667B1U static constexpr
Definition at line 270 of file crc.hpp.
The documentation for this class was generated from the following file:
pfc/crc.hpp