PFC - Prefix-Free Codecs: pfc::integrity::Adler32 Class Reference
pfc::integrity::Adler32 Class Reference
#include <pfc/crc.hpp>
Public Member Functions
Adler32 ()
void update (uint8_t byte)
void update (const uint8_t *data, size_t length)
void update (std::span< const uint8_t > data)
uint32_t finalize () const
void reset ()
Static Public Member Functions
static uint32_t calculate (const uint8_t *data, size_t length)
static uint32_t calculate (std::span< const uint8_t > data)
Static Public Attributes
static constexpr uint32_t mod_adler = 65521
Detailed Description
Definition at line 214 of file crc.hpp.
Constructor & Destructor Documentation
Adler32()
pfc::integrity::Adler32::Adler32 () inline
Definition at line 218 of file crc.hpp.
Member Function Documentation
calculate() [1/2]
static uint32_t pfc::integrity::Adler32::calculate (const uint8_t * data, size_t length) inline static
Definition at line 245 of file crc.hpp.
References finalize(), and update().
Referenced by calculate().
calculate() [2/2]
static uint32_t pfc::integrity::Adler32::calculate (std::span< const uint8_t > data) inline static
Definition at line 251 of file crc.hpp.
References calculate().
finalize()
uint32_t pfc::integrity::Adler32::finalize () const inline
Definition at line 236 of file crc.hpp.
Referenced by calculate().
reset()
void pfc::integrity::Adler32::reset () inline
Definition at line 240 of file crc.hpp.
update() [1/3]
void pfc::integrity::Adler32::update (const uint8_t * data, size_t length) inline
Definition at line 225 of file crc.hpp.
References mod_adler.
update() [2/3]
void pfc::integrity::Adler32::update (std::span< const uint8_t > data) inline
Definition at line 232 of file crc.hpp.
References update().
update() [3/3]
void pfc::integrity::Adler32::update (uint8_t byte) inline
Definition at line 220 of file crc.hpp.
References mod_adler.
Referenced by calculate(), and update().
Member Data Documentation
mod_adler
constexpr uint32_t pfc::integrity::Adler32::mod_adler = 65521 static constexpr
Definition at line 216 of file crc.hpp.
Referenced by update(), and update().
The documentation for this class was generated from the following file:
pfc/crc.hpp