PFC - Prefix-Free Codecs: pfc::SafeBitWriter< Allocator > Class Template Reference
pfc::SafeBitWriter< Allocator > Class Template Reference
#include <pfc/error_handling.hpp>
Public Types
using allocator_type = Allocator
using byte_allocator = typename std::allocator_traits< Allocator >::template rebind_alloc< uint8_t >
using buffer_type = std::vector< uint8_t, byte_allocator >
Public Member Functions
SafeBitWriter (size_t max_size, const Allocator &alloc=Allocator())
result< void > write_bit (bool b)
result< void > write_bits (uint64_t v, int n)
result< void > align ()
const buffer_type & buffer () const
size_t size () const
size_t bit_count () const
size_t max_size () const
allocator_type get_allocator () const
Detailed Description
template<typename Allocator = std::allocator<uint8_t>>
class pfc::SafeBitWriter< Allocator >
Definition at line 179 of file error_handling.hpp.
Member Typedef Documentation
allocator_type
template<typename Allocator = std::allocator<uint8_t>> using pfc::SafeBitWriter< Allocator >::allocator_type = Allocator
Definition at line 181 of file error_handling.hpp.
buffer_type
template<typename Allocator = std::allocator<uint8_t>> using pfc::SafeBitWriter< Allocator >::buffer_type = std::vector<uint8_t, byte_allocator>
Definition at line 183 of file error_handling.hpp.
byte_allocator
template<typename Allocator = std::allocator<uint8_t>> using pfc::SafeBitWriter< Allocator >::byte_allocator = typename std::allocator_traits<Allocator>::template rebind_alloc<uint8_t>
Definition at line 182 of file error_handling.hpp.
Constructor & Destructor Documentation
SafeBitWriter()
template<typename Allocator = std::allocator<uint8_t>> pfc::SafeBitWriter< Allocator >::SafeBitWriter (size_t max_size, const Allocator & alloc = Allocator()) inline explicit
Definition at line 185 of file error_handling.hpp.
References pfc::SafeBitWriter< Allocator >::max_size().
Member Function Documentation
align()
template<typename Allocator = std::allocator<uint8_t>> result< void > pfc::SafeBitWriter< Allocator >::align () inline
Definition at line 213 of file error_handling.hpp.
References pfc::buffer_overflow, and pfc::make_error_code().
bit_count()
template<typename Allocator = std::allocator<uint8_t>> size_t pfc::SafeBitWriter< Allocator >::bit_count () const inline
Definition at line 227 of file error_handling.hpp.
buffer()
template<typename Allocator = std::allocator<uint8_t>> const buffer_type & pfc::SafeBitWriter< Allocator >::buffer () const inline
Definition at line 225 of file error_handling.hpp.
get_allocator()
template<typename Allocator = std::allocator<uint8_t>> allocator_type pfc::SafeBitWriter< Allocator >::get_allocator () const inline
Definition at line 230 of file error_handling.hpp.
max_size()
template<typename Allocator = std::allocator<uint8_t>> size_t pfc::SafeBitWriter< Allocator >::max_size () const inline
Definition at line 228 of file error_handling.hpp.
Referenced by pfc::SafeBitWriter< Allocator >::SafeBitWriter().
size()
template<typename Allocator = std::allocator<uint8_t>> size_t pfc::SafeBitWriter< Allocator >::size () const inline
Definition at line 226 of file error_handling.hpp.
write_bit()
template<typename Allocator = std::allocator<uint8_t>> result< void > pfc::SafeBitWriter< Allocator >::write_bit (bool b) inline
Definition at line 190 of file error_handling.hpp.
References pfc::buffer_overflow, and pfc::make_error_code().
Referenced by pfc::SafeBitWriter< Allocator >::write_bits().
write_bits()
template<typename Allocator = std::allocator<uint8_t>> result< void > pfc::SafeBitWriter< Allocator >::write_bits (uint64_t v, int n) inline
Definition at line 204 of file error_handling.hpp.
References pfc::SafeBitWriter< Allocator >::write_bit().
The documentation for this class was generated from the following file:
pfc/error_handling.hpp