PFC - Prefix-Free Codecs: pfc::stream_bit_writer Class Reference
pfc::stream_bit_writer Class Reference
#include <pfc/stream_io.hpp>
Public Member Functions
stream_bit_writer (std::ostream &os, std::size_t buffer_size=8192)
stream_bit_writer (stream_bit_writer &&)=default
stream_bit_writer & operator= (stream_bit_writer &&)=default
void write (bool bit)
void write_bits (uint64_t bits, std::size_t count)
void write_bytes (const uint8_t *data, std::size_t size)
void align ()
void flush ()
std::size_t bytes_written () const noexcept
bool good () const noexcept
bool fail () const noexcept
bool bad () const noexcept
bool eof () const noexcept
operator bool () const noexcept
~stream_bit_writer ()
Detailed Description
Definition at line 120 of file stream_io.hpp.
Constructor & Destructor Documentation
stream_bit_writer() [1/2]
pfc::stream_bit_writer::stream_bit_writer (std::ostream & os, std::size_t buffer_size = 8192) inline explicit
Definition at line 128 of file stream_io.hpp.
stream_bit_writer() [2/2]
pfc::stream_bit_writer::stream_bit_writer (stream_bit_writer &&) default
~stream_bit_writer()
pfc::stream_bit_writer::~stream_bit_writer () inline
Definition at line 187 of file stream_io.hpp.
References flush().
Member Function Documentation
align()
void pfc::stream_bit_writer::align () inline
Definition at line 161 of file stream_io.hpp.
Referenced by flush(), and write_bytes().
bad()
bool pfc::stream_bit_writer::bad () const inline noexcept
Definition at line 183 of file stream_io.hpp.
bytes_written()
std::size_t pfc::stream_bit_writer::bytes_written () const inline noexcept
Definition at line 177 of file stream_io.hpp.
Referenced by pfc::write_compressed_file().
eof()
bool pfc::stream_bit_writer::eof () const inline noexcept
Definition at line 184 of file stream_io.hpp.
fail()
bool pfc::stream_bit_writer::fail () const inline noexcept
Definition at line 182 of file stream_io.hpp.
flush()
void pfc::stream_bit_writer::flush () inline
Definition at line 171 of file stream_io.hpp.
References align().
Referenced by pfc::compress_to_string(), pfc::operator<<(), pfc::write_compressed_file(), and ~stream_bit_writer().
good()
bool pfc::stream_bit_writer::good () const inline noexcept
Definition at line 181 of file stream_io.hpp.
Referenced by pfc::compress_to_string(), operator bool(), and pfc::write_compressed_file().
operator bool()
pfc::stream_bit_writer::operator bool () const inline explicit noexcept
Definition at line 185 of file stream_io.hpp.
References good().
operator=()
stream_bit_writer & pfc::stream_bit_writer::operator= (stream_bit_writer &&) default
write()
void pfc::stream_bit_writer::write (bool bit) inline
Definition at line 136 of file stream_io.hpp.
Referenced by write_bits().
write_bits()
void pfc::stream_bit_writer::write_bits (uint64_t bits, std::size_t count) inline
Definition at line 147 of file stream_io.hpp.
References write().
write_bytes()
void pfc::stream_bit_writer::write_bytes (const uint8_t * data, std::size_t size) inline
Definition at line 154 of file stream_io.hpp.
References align().
The documentation for this class was generated from the following file:
pfc/stream_io.hpp