PFC - Prefix-Free Codecs: pfc::succinct::BlockRankSupport Class Reference
pfc::succinct::BlockRankSupport Class Reference
#include <pfc/succinct.hpp>
Public Member Functions
BlockRankSupport ()=default
void build (const uint64_t *bits, size_t num_bits)
size_t rank (size_t pos) const
size_t select (size_t k) const
template<typename Sink >
requires BitSink<Sink>
void encode (Sink &sink) const
Static Public Member Functions
template<typename Source >
requires BitSource<Source>
static BlockRankSupport decode (Source &source, const uint64_t *bits)
Detailed Description
Definition at line 38 of file succinct.hpp.
Constructor & Destructor Documentation
BlockRankSupport()
pfc::succinct::BlockRankSupport::BlockRankSupport () default
Member Function Documentation
build()
void pfc::succinct::BlockRankSupport::build (const uint64_t * bits, size_t num_bits) inline
Definition at line 58 of file succinct.hpp.
Referenced by pfc::succinct::SuccinctBitVector::build_rank_support().
decode()
template<typename Source > requires BitSource<Source> static BlockRankSupport pfc::succinct::BlockRankSupport::decode (Source & source, const uint64_t * bits) inline static
Definition at line 197 of file succinct.hpp.
Referenced by pfc::succinct::SuccinctBitVector::decode().
encode()
template<typename Sink > requires BitSink<Sink> void pfc::succinct::BlockRankSupport::encode (Sink & sink) const inline
Definition at line 182 of file succinct.hpp.
References pfc::codecs::Fixed< Width >::encode(), and pfc::codecs::EliasGamma::encode().
rank()
size_t pfc::succinct::BlockRankSupport::rank (size_t pos) const inline
Definition at line 101 of file succinct.hpp.
Referenced by pfc::succinct::SuccinctBitVector::rank().
select()
size_t pfc::succinct::BlockRankSupport::select (size_t k) const inline
Definition at line 134 of file succinct.hpp.
Referenced by pfc::succinct::SuccinctBitVector::select().
The documentation for this class was generated from the following file:
pfc/succinct.hpp