PFC - Prefix-Free Codecs: pfc::codecs::StaticHuffman< Symbol, Allocator > Class Template Reference
pfc::codecs::StaticHuffman< Symbol, Allocator > Class Template Reference
#include <pfc/huffman.hpp>
Public Types
using symbol_type = Symbol
using allocator_type = Allocator
using frequency_map = std::unordered_map< Symbol, uint64_t >
using code_map = std::unordered_map< Symbol, std::pair< uint32_t, int > >
Public Member Functions
template<typename BitSink >
result< void > encode_symbol (Symbol symbol, BitSink &sink) const
template<typename BitSource >
result< Symbol > decode_symbol (BitSource &source) const
template<typename InputIt , typename BitSink >
result< size_t > encode (InputIt first, InputIt last, BitSink &sink) const
template<typename OutputIt , typename BitSource >
result< size_t > decode (BitSource &source, OutputIt out, size_t count) const
double average_code_length () const
template<typename BitSink >
result< void > write_header (BitSink &sink) const
Static Public Member Functions
static result< StaticHuffman > from_frequencies (const frequency_map &frequencies)
template<typename InputIt >
static result< StaticHuffman > from_data (InputIt first, InputIt last)
template<typename BitSource >
static result< StaticHuffman > read_header (BitSource &source)
Detailed Description
template<typename Symbol = uint8_t, typename Allocator = std::allocator<uint8_t>>
class pfc::codecs::StaticHuffman< Symbol, Allocator >
Definition at line 42 of file huffman.hpp.
Member Typedef Documentation
allocator_type
template<typename Symbol = uint8_t, typename Allocator = std::allocator<uint8_t>> using pfc::codecs::StaticHuffman< Symbol, Allocator >::allocator_type = Allocator
Definition at line 45 of file huffman.hpp.
code_map
template<typename Symbol = uint8_t, typename Allocator = std::allocator<uint8_t>> using pfc::codecs::StaticHuffman< Symbol, Allocator >::code_map = std::unordered_map<Symbol, std::pair<uint32_t, int> >
Definition at line 47 of file huffman.hpp.
frequency_map
template<typename Symbol = uint8_t, typename Allocator = std::allocator<uint8_t>> using pfc::codecs::StaticHuffman< Symbol, Allocator >::frequency_map = std::unordered_map<Symbol, uint64_t>
Definition at line 46 of file huffman.hpp.
symbol_type
template<typename Symbol = uint8_t, typename Allocator = std::allocator<uint8_t>> using pfc::codecs::StaticHuffman< Symbol, Allocator >::symbol_type = Symbol
Definition at line 44 of file huffman.hpp.
Member Function Documentation
average_code_length()
template<typename Symbol = uint8_t, typename Allocator = std::allocator<uint8_t>> double pfc::codecs::StaticHuffman< Symbol, Allocator >::average_code_length () const inline
Definition at line 148 of file huffman.hpp.
decode()
template<typename Symbol = uint8_t, typename Allocator = std::allocator<uint8_t>> template<typename OutputIt , typename BitSource > result< size_t > pfc::codecs::StaticHuffman< Symbol, Allocator >::decode (BitSource & source, OutputIt out, size_t count) const inline
Definition at line 136 of file huffman.hpp.
References pfc::codecs::StaticHuffman< Symbol, Allocator >::decode_symbol().
decode_symbol()
template<typename Symbol = uint8_t, typename Allocator = std::allocator<uint8_t>> template<typename BitSource > result< Symbol > pfc::codecs::StaticHuffman< Symbol, Allocator >::decode_symbol (BitSource & source) const inline
Definition at line 98 of file huffman.hpp.
References pfc::corrupted_data, pfc::incomplete_data, pfc::invalid_input, pfc::codecs::HuffmanNode< Symbol >::is_leaf(), pfc::codecs::HuffmanNode< Symbol >::left, pfc::make_error_code(), pfc::codecs::HuffmanNode< Symbol >::right, and pfc::codecs::HuffmanNode< Symbol >::symbol.
Referenced by pfc::codecs::StaticHuffman< Symbol, Allocator >::decode().
encode()
template<typename Symbol = uint8_t, typename Allocator = std::allocator<uint8_t>> template<typename InputIt , typename BitSink > result< size_t > pfc::codecs::StaticHuffman< Symbol, Allocator >::encode (InputIt first, InputIt last, BitSink & sink) const inline
Definition at line 123 of file huffman.hpp.
References pfc::codecs::StaticHuffman< Symbol, Allocator >::encode_symbol().
encode_symbol()
template<typename Symbol = uint8_t, typename Allocator = std::allocator<uint8_t>> template<typename BitSink > result< void > pfc::codecs::StaticHuffman< Symbol, Allocator >::encode_symbol (Symbol symbol, BitSink & sink) const inline
Definition at line 83 of file huffman.hpp.
References pfc::invalid_input, and pfc::make_error_code().
Referenced by pfc::codecs::StaticHuffman< Symbol, Allocator >::encode().
from_data()
template<typename Symbol = uint8_t, typename Allocator = std::allocator<uint8_t>> template<typename InputIt > static result< StaticHuffman > pfc::codecs::StaticHuffman< Symbol, Allocator >::from_data (InputIt first, InputIt last) inline static
Definition at line 73 of file huffman.hpp.
References pfc::codecs::StaticHuffman< Symbol, Allocator >::from_frequencies().
from_frequencies()
template<typename Symbol = uint8_t, typename Allocator = std::allocator<uint8_t>> static result< StaticHuffman > pfc::codecs::StaticHuffman< Symbol, Allocator >::from_frequencies (const frequency_map & frequencies) inline static
Definition at line 50 of file huffman.hpp.
References pfc::compression_error, pfc::invalid_input, and pfc::make_error_code().
Referenced by pfc::codecs::StaticHuffman< Symbol, Allocator >::from_data(), pfc::codecs::CanonicalHuffman< Symbol >::from_frequencies(), and pfc::codecs::StaticHuffman< Symbol, Allocator >::read_header().
read_header()
template<typename Symbol = uint8_t, typename Allocator = std::allocator<uint8_t>> template<typename BitSource > static result< StaticHuffman > pfc::codecs::StaticHuffman< Symbol, Allocator >::read_header (BitSource & source) inline static
Definition at line 191 of file huffman.hpp.
References pfc::codecs::StaticHuffman< Symbol, Allocator >::from_frequencies(), pfc::incomplete_data, pfc::invalid_header, and pfc::make_error_code().
write_header()
template<typename Symbol = uint8_t, typename Allocator = std::allocator<uint8_t>> template<typename BitSink > result< void > pfc::codecs::StaticHuffman< Symbol, Allocator >::write_header (BitSink & sink) const inline
Definition at line 167 of file huffman.hpp.
The documentation for this class was generated from the following file:
pfc/huffman.hpp