PFC - Prefix-Free Codecs: pfc::range_encoder Class Reference
pfc::range_encoder Class Reference
#include <pfc/arithmetic_coding.hpp>
Public Member Functions
range_encoder (BitWriter &sink)
template<ProbabilityModel Model>
void encode_symbol (std::size_t symbol, Model &model)
void encode_bit (bool bit, uint32_t prob_zero)
void finish ()
Detailed Description
Definition at line 383 of file arithmetic_coding.hpp.
Constructor & Destructor Documentation
range_encoder()
pfc::range_encoder::range_encoder (BitWriter & sink) inline explicit
Definition at line 401 of file arithmetic_coding.hpp.
Member Function Documentation
encode_bit()
void pfc::range_encoder::encode_bit (bool bit, uint32_t prob_zero) inline
Definition at line 424 of file arithmetic_coding.hpp.
encode_symbol()
template<ProbabilityModel Model> void pfc::range_encoder::encode_symbol (std::size_t symbol, Model & model) inline
Definition at line 404 of file arithmetic_coding.hpp.
Referenced by pfc::RangeCodec< T, Symbols >::encode(), and pfc::range_compress().
finish()
void pfc::range_encoder::finish () inline
Definition at line 438 of file arithmetic_coding.hpp.
References pfc::BitWriter::write_bits().
Referenced by pfc::RangeCodec< T, Symbols >::encode(), and pfc::range_compress().
The documentation for this class was generated from the following file:
pfc/arithmetic_coding.hpp