PFC - Prefix-Free Codecs: pfc::result< void > Class Reference
pfc::result< void > Class Reference
#include <pfc/error_handling.hpp>
Public Member Functions
result ()
result (std::error_code ec)
bool has_value () const
operator bool () const
void value () const
std::error_code error () const
Detailed Description
Definition at line 152 of file error_handling.hpp.
Constructor & Destructor Documentation
result() [1/2]
pfc::result< void >::result () inline
Definition at line 154 of file error_handling.hpp.
result() [2/2]
pfc::result< void >::result (std::error_code ec) inline
Definition at line 155 of file error_handling.hpp.
Member Function Documentation
error()
std::error_code pfc::result< void >::error () const inline
Definition at line 164 of file error_handling.hpp.
has_value()
bool pfc::result< void >::has_value () const inline
Definition at line 157 of file error_handling.hpp.
operator bool()
pfc::result< void >::operator bool () const inline explicit
Definition at line 158 of file error_handling.hpp.
References pfc::result< T >::has_value().
value()
void pfc::result< void >::value () const inline
Definition at line 160 of file error_handling.hpp.
References pfc::result< T >::error(), and pfc::result< T >::has_value().
The documentation for this class was generated from the following file:
pfc/error_handling.hpp