PFC - Prefix-Free Codecs: pfc::PackedSharedPtr< T > Class Template Reference
pfc::PackedSharedPtr< T > Class Template Reference
#include <pfc/algebraic.hpp>
Public Types
using value_type = std::shared_ptr< T >
Public Member Functions
PackedSharedPtr ()=default
PackedSharedPtr (const value_type &p)
PackedSharedPtr (value_type &&p)
const value_type & value () const noexcept
value_type & value () noexcept
Static Public Member Functions
template<typename Sink >
requires BitSink<Sink>
static void encode (const PackedSharedPtr &p, Sink &sink)
template<typename Source >
requires BitSource<Source>
static PackedSharedPtr decode (Source &source)
Detailed Description
template<typename T>
class pfc::PackedSharedPtr< T >
Definition at line 218 of file algebraic.hpp.
Member Typedef Documentation
value_type
template<typename T > using pfc::PackedSharedPtr< T >::value_type = std::shared_ptr<T>
Definition at line 220 of file algebraic.hpp.
Constructor & Destructor Documentation
PackedSharedPtr() [1/3]
template<typename T > pfc::PackedSharedPtr< T >::PackedSharedPtr () default
PackedSharedPtr() [2/3]
template<typename T > pfc::PackedSharedPtr< T >::PackedSharedPtr (const value_type & p) inline explicit
Definition at line 227 of file algebraic.hpp.
PackedSharedPtr() [3/3]
template<typename T > pfc::PackedSharedPtr< T >::PackedSharedPtr (value_type && p) inline explicit
Definition at line 228 of file algebraic.hpp.
Member Function Documentation
decode()
template<typename T > template<typename Source > requires BitSource<Source> static PackedSharedPtr pfc::PackedSharedPtr< T >::decode (Source & source) inline static
Definition at line 243 of file algebraic.hpp.
References pfc::codecs::Boolean::decode().
encode()
template<typename T > template<typename Sink > requires BitSink<Sink> static void pfc::PackedSharedPtr< T >::encode (const PackedSharedPtr< T > & p, Sink & sink) inline static
Definition at line 235 of file algebraic.hpp.
References pfc::codecs::Boolean::encode().
value() [1/2]
template<typename T > const value_type & pfc::PackedSharedPtr< T >::value () const inline noexcept
Definition at line 230 of file algebraic.hpp.
Referenced by pfc::PackedTree< Value >::left(), and pfc::PackedTree< Value >::right().
value() [2/2]
template<typename T > value_type & pfc::PackedSharedPtr< T >::value () inline noexcept
Definition at line 231 of file algebraic.hpp.
The documentation for this class was generated from the following file:
pfc/algebraic.hpp