PFC - Prefix-Free Codecs: pfc::PackedOptional< T > Class Template Reference
pfc::PackedOptional< T > Class Template Reference
#include <pfc/packed.hpp>
Public Types
using value_type = std::optional< typename T::value_type >
Public Member Functions
PackedOptional ()=default
PackedOptional (std::nullopt_t)
PackedOptional (const T &val)
PackedOptional (T &&val)
PackedOptional (const value_type &val)
bool has_value () const noexcept
operator bool () const noexcept
const T & operator* () const
T & operator* ()
const T * operator-> () const
T * operator-> ()
value_type value () const
Static Public Member Functions
template<typename Sink >
requires BitSink<Sink>
static void encode (const PackedOptional &p, Sink &sink)
template<typename Source >
requires BitSource<Source>
static PackedOptional decode (Source &source)
Detailed Description
template<PackedValue T>
class pfc::PackedOptional< T >
Definition at line 216 of file packed.hpp.
Member Typedef Documentation
value_type
template<PackedValue T> using pfc::PackedOptional< T >::value_type = std::optional<typename T::value_type>
Definition at line 218 of file packed.hpp.
Constructor & Destructor Documentation
PackedOptional() [1/5]
template<PackedValue T> pfc::PackedOptional< T >::PackedOptional () default
PackedOptional() [2/5]
template<PackedValue T> pfc::PackedOptional< T >::PackedOptional (std::nullopt_t) inline
Definition at line 226 of file packed.hpp.
PackedOptional() [3/5]
template<PackedValue T> pfc::PackedOptional< T >::PackedOptional (const T & val) inline explicit
Definition at line 228 of file packed.hpp.
PackedOptional() [4/5]
template<PackedValue T> pfc::PackedOptional< T >::PackedOptional (T && val) inline explicit
Definition at line 229 of file packed.hpp.
PackedOptional() [5/5]
template<PackedValue T> pfc::PackedOptional< T >::PackedOptional (const value_type & val) inline explicit
Definition at line 231 of file packed.hpp.
Member Function Documentation
decode()
template<PackedValue T> template<typename Source > requires BitSource<Source> static PackedOptional pfc::PackedOptional< T >::decode (Source & source) inline static
Definition at line 260 of file packed.hpp.
References pfc::codecs::Boolean::decode().
encode()
template<PackedValue T> template<typename Sink > requires BitSink<Sink> static void pfc::PackedOptional< T >::encode (const PackedOptional< T > & p, Sink & sink) inline static
Definition at line 252 of file packed.hpp.
References pfc::codecs::Boolean::encode().
has_value()
template<PackedValue T> bool pfc::PackedOptional< T >::has_value () const inline noexcept
Definition at line 235 of file packed.hpp.
Referenced by pfc::PackedOptional< T >::operator bool().
operator bool()
template<PackedValue T> pfc::PackedOptional< T >::operator bool () const inline explicit noexcept
Definition at line 236 of file packed.hpp.
References pfc::PackedOptional< T >::has_value().
operator*() [1/2]
template<PackedValue T> T & pfc::PackedOptional< T >::operator* () inline
Definition at line 240 of file packed.hpp.
operator*() [2/2]
template<PackedValue T> const T & pfc::PackedOptional< T >::operator* () const inline
Definition at line 239 of file packed.hpp.
operator->() [1/2]
template<PackedValue T> T * pfc::PackedOptional< T >::operator-> () inline
Definition at line 243 of file packed.hpp.
operator->() [2/2]
template<PackedValue T> const T * pfc::PackedOptional< T >::operator-> () const inline
Definition at line 242 of file packed.hpp.
value()
template<PackedValue T> value_type pfc::PackedOptional< T >::value () const inline
Definition at line 246 of file packed.hpp.
The documentation for this class was generated from the following file:
pfc/packed.hpp