PFC - Prefix-Free Codecs: pfc::BasicPackedBuffer< Allocator > Class Template Reference
pfc::BasicPackedBuffer< Allocator > Class Template Reference
#include <pfc/allocator_support.hpp>
Public Types
using allocator_type = Allocator
using buffer_type = std::vector< uint8_t, Allocator >
Public Member Functions
BasicPackedBuffer (const Allocator &alloc=Allocator())
template<typename T , typename Codec >
void pack (const T &value)
template<typename T , typename Codec >
T unpack (size_t &offset) const
const buffer_type & data () const
size_t size () const
allocator_type get_allocator () const
void clear ()
void reserve (size_t n)
Detailed Description
template<typename Allocator = std::allocator<uint8_t>>
class pfc::BasicPackedBuffer< Allocator >
Definition at line 152 of file allocator_support.hpp.
Member Typedef Documentation
allocator_type
template<typename Allocator = std::allocator<uint8_t>> using pfc::BasicPackedBuffer< Allocator >::allocator_type = Allocator
Definition at line 154 of file allocator_support.hpp.
buffer_type
template<typename Allocator = std::allocator<uint8_t>> using pfc::BasicPackedBuffer< Allocator >::buffer_type = std::vector<uint8_t, Allocator>
Definition at line 155 of file allocator_support.hpp.
Constructor & Destructor Documentation
BasicPackedBuffer()
template<typename Allocator = std::allocator<uint8_t>> pfc::BasicPackedBuffer< Allocator >::BasicPackedBuffer (const Allocator & alloc = Allocator()) inline explicit
Definition at line 157 of file allocator_support.hpp.
Member Function Documentation
clear()
template<typename Allocator = std::allocator<uint8_t>> void pfc::BasicPackedBuffer< Allocator >::clear () inline
Definition at line 186 of file allocator_support.hpp.
data()
template<typename Allocator = std::allocator<uint8_t>> const buffer_type & pfc::BasicPackedBuffer< Allocator >::data () const inline
Definition at line 179 of file allocator_support.hpp.
get_allocator()
template<typename Allocator = std::allocator<uint8_t>> allocator_type pfc::BasicPackedBuffer< Allocator >::get_allocator () const inline
Definition at line 182 of file allocator_support.hpp.
Referenced by pfc::BasicPackedBuffer< Allocator >::pack().
pack()
template<typename Allocator = std::allocator<uint8_t>> template<typename T , typename Codec > void pfc::BasicPackedBuffer< Allocator >::pack (const T & value) inline
Definition at line 161 of file allocator_support.hpp.
References pfc::BasicBitWriter< Allocator >::align(), pfc::BasicBitWriter< Allocator >::buffer(), and pfc::BasicPackedBuffer< Allocator >::get_allocator().
reserve()
template<typename Allocator = std::allocator<uint8_t>> void pfc::BasicPackedBuffer< Allocator >::reserve (size_t n) inline
Definition at line 187 of file allocator_support.hpp.
size()
template<typename Allocator = std::allocator<uint8_t>> size_t pfc::BasicPackedBuffer< Allocator >::size () const inline
Definition at line 180 of file allocator_support.hpp.
unpack()
template<typename Allocator = std::allocator<uint8_t>> template<typename T , typename Codec > T pfc::BasicPackedBuffer< Allocator >::unpack (size_t & offset) const inline
Definition at line 172 of file allocator_support.hpp.
References pfc::BasicBitReader< Allocator >::position().
The documentation for this class was generated from the following file:
pfc/allocator_support.hpp