PFC - Prefix-Free Codecs: pfc::PackedAffineTransform< N, Scalar > Class Template Reference
pfc::PackedAffineTransform< N, Scalar > Class Template Reference
#include <pfc/coordinates.hpp>
Public Types
using matrix_type = PackedMatrix< N, N, Scalar >
using vector_type = PackedVec< N, Scalar >
using scalar_type = typename Scalar::value_type
Public Member Functions
PackedAffineTransform ()
PackedAffineTransform (const matrix_type &m, const vector_type &t)
vector_type transform_point (const vector_type &p) const
vector_type transform_vector (const vector_type &v) const
PackedAffineTransform operator* (const PackedAffineTransform &other) const
Static Public Member Functions
static PackedAffineTransform translation (const vector_type &t)
static PackedAffineTransform scale (scalar_type s)
static PackedAffineTransform rotation_2d (scalar_type angle)
template<typename Sink >
requires BitSink<Sink>
static void encode (const PackedAffineTransform &t, Sink &sink)
template<typename Source >
requires BitSource<Source>
static PackedAffineTransform decode (Source &source)
Detailed Description
template<size_t N, PackedValue Scalar = Packed<double, codecs::Float32>>
class pfc::PackedAffineTransform< N, Scalar >
Definition at line 506 of file coordinates.hpp.
Member Typedef Documentation
matrix_type
template<size_t N, PackedValue Scalar = Packed<double, codecs::Float32>> using pfc::PackedAffineTransform< N, Scalar >::matrix_type = PackedMatrix<N, N, Scalar>
Definition at line 508 of file coordinates.hpp.
scalar_type
template<size_t N, PackedValue Scalar = Packed<double, codecs::Float32>> using pfc::PackedAffineTransform< N, Scalar >::scalar_type = typename Scalar::value_type
Definition at line 510 of file coordinates.hpp.
vector_type
template<size_t N, PackedValue Scalar = Packed<double, codecs::Float32>> using pfc::PackedAffineTransform< N, Scalar >::vector_type = PackedVec<N, Scalar>
Definition at line 509 of file coordinates.hpp.
Constructor & Destructor Documentation
PackedAffineTransform() [1/2]
template<size_t N, PackedValue Scalar = Packed<double, codecs::Float32>> pfc::PackedAffineTransform< N, Scalar >::PackedAffineTransform () inline
Definition at line 518 of file coordinates.hpp.
PackedAffineTransform() [2/2]
template<size_t N, PackedValue Scalar = Packed<double, codecs::Float32>> pfc::PackedAffineTransform< N, Scalar >::PackedAffineTransform (const matrix_type & m, const vector_type & t) inline
Definition at line 521 of file coordinates.hpp.
Member Function Documentation
decode()
template<size_t N, PackedValue Scalar = Packed<double, codecs::Float32>> template<typename Source > requires BitSource<Source> static PackedAffineTransform pfc::PackedAffineTransform< N, Scalar >::decode (Source & source) inline static
Definition at line 575 of file coordinates.hpp.
References pfc::PackedVec< N, Component >::decode(), and pfc::PackedMatrix< Rows, Cols, Element >::decode().
encode()
template<size_t N, PackedValue Scalar = Packed<double, codecs::Float32>> template<typename Sink > requires BitSink<Sink> static void pfc::PackedAffineTransform< N, Scalar >::encode (const PackedAffineTransform< N, Scalar > & t, Sink & sink) inline static
Definition at line 569 of file coordinates.hpp.
References pfc::PackedMatrix< Rows, Cols, Element >::encode(), and pfc::PackedVec< N, Component >::encode().
operator*()
template<size_t N, PackedValue Scalar = Packed<double, codecs::Float32>> PackedAffineTransform pfc::PackedAffineTransform< N, Scalar >::operator* (const PackedAffineTransform< N, Scalar > & other) const inline
Definition at line 535 of file coordinates.hpp.
rotation_2d()
template<size_t N, PackedValue Scalar = Packed<double, codecs::Float32>> static PackedAffineTransform pfc::PackedAffineTransform< N, Scalar >::rotation_2d (scalar_type angle) inline static
Definition at line 557 of file coordinates.hpp.
scale()
template<size_t N, PackedValue Scalar = Packed<double, codecs::Float32>> static PackedAffineTransform pfc::PackedAffineTransform< N, Scalar >::scale (scalar_type s) inline static
Definition at line 547 of file coordinates.hpp.
References pfc::PackedMatrix< Rows, Cols, Element >::identity().
transform_point()
template<size_t N, PackedValue Scalar = Packed<double, codecs::Float32>> vector_type pfc::PackedAffineTransform< N, Scalar >::transform_point (const vector_type & p) const inline
Definition at line 525 of file coordinates.hpp.
transform_vector()
template<size_t N, PackedValue Scalar = Packed<double, codecs::Float32>> vector_type pfc::PackedAffineTransform< N, Scalar >::transform_vector (const vector_type & v) const inline
Definition at line 530 of file coordinates.hpp.
translation()
template<size_t N, PackedValue Scalar = Packed<double, codecs::Float32>> static PackedAffineTransform pfc::PackedAffineTransform< N, Scalar >::translation (const vector_type & t) inline static
Definition at line 543 of file coordinates.hpp.
References pfc::PackedMatrix< Rows, Cols, Element >::identity().
The documentation for this class was generated from the following file:
pfc/coordinates.hpp