PFC - Prefix-Free Codecs: pfc::PackedContainer< Element > Class Template Reference
pfc::PackedContainer< Element > Class Template Reference
#include <pfc/stl_integration.hpp>
Public Types
using value_type = typename Element::value_type
using size_type = size_t
using difference_type = std::ptrdiff_t
using iterator = PackedIterator< Element, PackedContainer >
using const_iterator = PackedIterator< Element, const PackedContainer >
Public Member Functions
PackedContainer ()=default
template<typename InputIt >
PackedContainer (InputIt first, InputIt last)
size_type size () const noexcept
bool empty () const noexcept
void reserve (size_type new_cap)
void clear () noexcept
value_type operator[] (size_type pos) const
value_type at (size_type pos) const
value_type front () const
value_type back () const
void push_back (const Element &elem)
void push_back (Element &&elem)
template<typename... Args>
void emplace_back (Args &&... args)
void pop_back ()
iterator begin () noexcept
iterator end () noexcept
const_iterator begin () const noexcept
const_iterator end () const noexcept
const_iterator cbegin () const noexcept
const_iterator cend () const noexcept
std::span< const uint8_t > raw_data (size_t index) const
void update_element (size_t index, const Element &elem)
size_type capacity () const noexcept
size_type data_bytes () const noexcept
double compression_ratio () const noexcept
Detailed Description
template<PackedValue Element>
class pfc::PackedContainer< Element >
Definition at line 180 of file stl_integration.hpp.
Member Typedef Documentation
const_iterator
template<PackedValue Element> using pfc::PackedContainer< Element >::const_iterator = PackedIterator<Element, const PackedContainer>
Definition at line 186 of file stl_integration.hpp.
difference_type
template<PackedValue Element> using pfc::PackedContainer< Element >::difference_type = std::ptrdiff_t
Definition at line 184 of file stl_integration.hpp.
iterator
template<PackedValue Element> using pfc::PackedContainer< Element >::iterator = PackedIterator<Element, PackedContainer>
Definition at line 185 of file stl_integration.hpp.
size_type
template<PackedValue Element> using pfc::PackedContainer< Element >::size_type = size_t
Definition at line 183 of file stl_integration.hpp.
value_type
template<PackedValue Element> using pfc::PackedContainer< Element >::value_type = typename Element::value_type
Definition at line 182 of file stl_integration.hpp.
Constructor & Destructor Documentation
PackedContainer() [1/2]
template<PackedValue Element> pfc::PackedContainer< Element >::PackedContainer () default
PackedContainer() [2/2]
template<PackedValue Element> template<typename InputIt > pfc::PackedContainer< Element >::PackedContainer (InputIt first, InputIt last) inline
Definition at line 199 of file stl_integration.hpp.
References pfc::PackedContainer< Element >::push_back().
Member Function Documentation
at()
template<PackedValue Element> value_type pfc::PackedContainer< Element >::at (size_type pos) const inline
Definition at line 228 of file stl_integration.hpp.
back()
template<PackedValue Element> value_type pfc::PackedContainer< Element >::back () const inline
Definition at line 236 of file stl_integration.hpp.
begin() [1/2]
template<PackedValue Element> const_iterator pfc::PackedContainer< Element >::begin () const inline noexcept
Definition at line 281 of file stl_integration.hpp.
begin() [2/2]
template<PackedValue Element> iterator pfc::PackedContainer< Element >::begin () inline noexcept
Definition at line 279 of file stl_integration.hpp.
Referenced by pfc::PackedContainer< Element >::cbegin(), and pfc::algorithms::packed_transform_par().
capacity()
template<PackedValue Element> size_type pfc::PackedContainer< Element >::capacity () const inline noexcept
Definition at line 317 of file stl_integration.hpp.
cbegin()
template<PackedValue Element> const_iterator pfc::PackedContainer< Element >::cbegin () const inline noexcept
Definition at line 283 of file stl_integration.hpp.
References pfc::PackedContainer< Element >::begin().
cend()
template<PackedValue Element> const_iterator pfc::PackedContainer< Element >::cend () const inline noexcept
Definition at line 284 of file stl_integration.hpp.
References pfc::PackedContainer< Element >::end().
clear()
template<PackedValue Element> void pfc::PackedContainer< Element >::clear () inline noexcept
Definition at line 215 of file stl_integration.hpp.
Referenced by pfc::sort().
compression_ratio()
template<PackedValue Element> double pfc::PackedContainer< Element >::compression_ratio () const inline noexcept
Definition at line 326 of file stl_integration.hpp.
data_bytes()
template<PackedValue Element> size_type pfc::PackedContainer< Element >::data_bytes () const inline noexcept
Definition at line 321 of file stl_integration.hpp.
emplace_back()
template<PackedValue Element> template<typename... Args> void pfc::PackedContainer< Element >::emplace_back (Args &&... args) inline
Definition at line 266 of file stl_integration.hpp.
References pfc::PackedContainer< Element >::push_back().
empty()
template<PackedValue Element> bool pfc::PackedContainer< Element >::empty () const inline noexcept
Definition at line 207 of file stl_integration.hpp.
end() [1/2]
template<PackedValue Element> const_iterator pfc::PackedContainer< Element >::end () const inline noexcept
Definition at line 282 of file stl_integration.hpp.
end() [2/2]
template<PackedValue Element> iterator pfc::PackedContainer< Element >::end () inline noexcept
Definition at line 280 of file stl_integration.hpp.
Referenced by pfc::PackedContainer< Element >::cend(), and pfc::algorithms::packed_transform_par().
front()
template<PackedValue Element> value_type pfc::PackedContainer< Element >::front () const inline
Definition at line 235 of file stl_integration.hpp.
operator[]()
template<PackedValue Element> value_type pfc::PackedContainer< Element >::operator[] (size_type pos) const inline
Definition at line 222 of file stl_integration.hpp.
pop_back()
template<PackedValue Element> void pfc::PackedContainer< Element >::pop_back () inline
Definition at line 270 of file stl_integration.hpp.
push_back() [1/2]
template<PackedValue Element> void pfc::PackedContainer< Element >::push_back (const Element & elem) inline
Definition at line 239 of file stl_integration.hpp.
References pfc::BitWriter::align(), and pfc::BitWriter::bytes_written().
Referenced by pfc::PackedContainer< Element >::emplace_back(), pfc::PackedContainer< Element >::PackedContainer(), pfc::PackedContainer< Element >::push_back(), pfc::sort(), and pfc::PackedContainer< Element >::update_element().
push_back() [2/2]
template<PackedValue Element> void pfc::PackedContainer< Element >::push_back (Element && elem) inline
Definition at line 261 of file stl_integration.hpp.
References pfc::PackedContainer< Element >::push_back().
raw_data()
template<PackedValue Element> std::span< const uint8_t > pfc::PackedContainer< Element >::raw_data (size_t index) const inline
Definition at line 287 of file stl_integration.hpp.
Referenced by pfc::algorithms::packed_merge().
reserve()
template<PackedValue Element> void pfc::PackedContainer< Element >::reserve (size_type new_cap) inline
Definition at line 209 of file stl_integration.hpp.
size()
template<PackedValue Element> size_type pfc::PackedContainer< Element >::size () const inline noexcept
Definition at line 206 of file stl_integration.hpp.
Referenced by pfc::algorithms::packed_accumulate(), pfc::algorithms::packed_find_if(), pfc::algorithms::packed_merge(), pfc::algorithms::packed_transform(), pfc::algorithms::packed_transform_par(), and pfc::sort().
update_element()
template<PackedValue Element> void pfc::PackedContainer< Element >::update_element (size_t index, const Element & elem) inline
Definition at line 292 of file stl_integration.hpp.
References pfc::PackedContainer< Element >::push_back().
The documentation for this class was generated from the following file:
pfc/stl_integration.hpp