PFC - Prefix-Free Codecs: pfc::stream_bit_reader Class Reference
pfc::stream_bit_reader Class Reference
#include <pfc/stream_io.hpp>
Public Member Functions
stream_bit_reader (std::istream &is, std::size_t buffer_size=8192)
stream_bit_reader (stream_bit_reader &&)=default
stream_bit_reader & operator= (stream_bit_reader &&)=default
bool peek () const noexcept
bool read ()
uint64_t read_bits (std::size_t count)
std::size_t read_bytes (uint8_t *data, std::size_t size)
void align ()
std::size_t bytes_read () const noexcept
bool good () const noexcept
bool fail () const noexcept
bool bad () const noexcept
bool eof () const noexcept
operator bool () const noexcept
Detailed Description
Definition at line 198 of file stream_io.hpp.
Constructor & Destructor Documentation
stream_bit_reader() [1/2]
pfc::stream_bit_reader::stream_bit_reader (std::istream & is, std::size_t buffer_size = 8192) inline explicit
Definition at line 207 of file stream_io.hpp.
stream_bit_reader() [2/2]
pfc::stream_bit_reader::stream_bit_reader (stream_bit_reader &&) default
Member Function Documentation
align()
void pfc::stream_bit_reader::align () inline
Definition at line 256 of file stream_io.hpp.
Referenced by read_bytes().
bad()
bool pfc::stream_bit_reader::bad () const inline noexcept
Definition at line 267 of file stream_io.hpp.
Referenced by pfc::decompress_from_string(), and pfc::read_compressed_file().
bytes_read()
std::size_t pfc::stream_bit_reader::bytes_read () const inline noexcept
Definition at line 261 of file stream_io.hpp.
eof()
bool pfc::stream_bit_reader::eof () const inline noexcept
Definition at line 268 of file stream_io.hpp.
fail()
bool pfc::stream_bit_reader::fail () const inline noexcept
Definition at line 266 of file stream_io.hpp.
Referenced by pfc::decompress_from_string(), and pfc::read_compressed_file().
good()
bool pfc::stream_bit_reader::good () const inline noexcept
Definition at line 265 of file stream_io.hpp.
Referenced by operator bool().
operator bool()
pfc::stream_bit_reader::operator bool () const inline explicit noexcept
Definition at line 269 of file stream_io.hpp.
References good().
operator=()
stream_bit_reader & pfc::stream_bit_reader::operator= (stream_bit_reader &&) default
peek()
bool pfc::stream_bit_reader::peek () const inline noexcept
Definition at line 215 of file stream_io.hpp.
read()
bool pfc::stream_bit_reader::read () inline
Definition at line 219 of file stream_io.hpp.
Referenced by read_bits().
read_bits()
uint64_t pfc::stream_bit_reader::read_bits (std::size_t count) inline
Definition at line 238 of file stream_io.hpp.
References read().
read_bytes()
std::size_t pfc::stream_bit_reader::read_bytes (uint8_t * data, std::size_t size) inline
Definition at line 247 of file stream_io.hpp.
References align().
The documentation for this class was generated from the following file:
pfc/stream_io.hpp