PFC - Prefix-Free Codecs: pfc::succinct::SuccinctBitVector Class Reference
pfc::succinct::SuccinctBitVector Class Reference
#include <pfc/succinct.hpp>
Public Types
using value_type = bool
using size_type = size_t
Public Member Functions
SuccinctBitVector ()=default
SuccinctBitVector (size_t num_bits, bool initial_value=false)
SuccinctBitVector (std::initializer_list< bool > bits)
void build_rank_support ()
size_t size () const noexcept
size_t num_words () const noexcept
bool empty () const noexcept
bool operator[] (size_t pos) const
bool test (size_t pos) const
void set (size_t pos, bool value=true)
void reset (size_t pos)
void flip (size_t pos)
size_t rank (size_t pos) const
size_t select (size_t k) const
const uint64_t * data () const noexcept
std::span< const uint64_t > words () const noexcept
Static Public Member Functions
template<typename Sink >
requires BitSink<Sink>
static void encode (const SuccinctBitVector &bv, Sink &sink)
template<typename Source >
requires BitSource<Source>
static SuccinctBitVector decode (Source &source)
Detailed Description
Definition at line 226 of file succinct.hpp.
Member Typedef Documentation
size_type
using pfc::succinct::SuccinctBitVector::size_type = size_t
Definition at line 234 of file succinct.hpp.
value_type
using pfc::succinct::SuccinctBitVector::value_type = bool
Definition at line 233 of file succinct.hpp.
Constructor & Destructor Documentation
SuccinctBitVector() [1/3]
pfc::succinct::SuccinctBitVector::SuccinctBitVector () default
SuccinctBitVector() [2/3]
pfc::succinct::SuccinctBitVector::SuccinctBitVector (size_t num_bits, bool initial_value = false) inline explicit
Definition at line 238 of file succinct.hpp.
SuccinctBitVector() [3/3]
pfc::succinct::SuccinctBitVector::SuccinctBitVector (std::initializer_list< bool > bits) inline
Definition at line 251 of file succinct.hpp.
References build_rank_support(), and set().
Member Function Documentation
build_rank_support()
void pfc::succinct::SuccinctBitVector::build_rank_support () inline
Definition at line 264 of file succinct.hpp.
References pfc::succinct::BlockRankSupport::build().
Referenced by SuccinctBitVector().
data()
const uint64_t * pfc::succinct::SuccinctBitVector::data () const inline noexcept
Definition at line 316 of file succinct.hpp.
decode()
template<typename Source > requires BitSource<Source> static SuccinctBitVector pfc::succinct::SuccinctBitVector::decode (Source & source) inline static
Definition at line 344 of file succinct.hpp.
References pfc::succinct::BlockRankSupport::decode(), and num_words().
empty()
bool pfc::succinct::SuccinctBitVector::empty () const inline noexcept
Definition at line 271 of file succinct.hpp.
encode()
template<typename Sink > requires BitSink<Sink> static void pfc::succinct::SuccinctBitVector::encode (const SuccinctBitVector & bv, Sink & sink) inline static
Definition at line 326 of file succinct.hpp.
References pfc::codecs::EliasGamma::encode().
flip()
void pfc::succinct::SuccinctBitVector::flip (size_t pos) inline
Definition at line 299 of file succinct.hpp.
num_words()
size_t pfc::succinct::SuccinctBitVector::num_words () const inline noexcept
Definition at line 270 of file succinct.hpp.
Referenced by decode().
operator[]()
bool pfc::succinct::SuccinctBitVector::operator[] (size_t pos) const inline
Definition at line 274 of file succinct.hpp.
rank()
size_t pfc::succinct::SuccinctBitVector::rank (size_t pos) const inline
Definition at line 306 of file succinct.hpp.
References pfc::succinct::BlockRankSupport::rank().
reset()
void pfc::succinct::SuccinctBitVector::reset (size_t pos) inline
Definition at line 295 of file succinct.hpp.
References set().
select()
size_t pfc::succinct::SuccinctBitVector::select (size_t k) const inline
Definition at line 311 of file succinct.hpp.
References pfc::succinct::BlockRankSupport::select().
set()
void pfc::succinct::SuccinctBitVector::set (size_t pos, bool value = true) inline
Definition at line 285 of file succinct.hpp.
Referenced by reset(), and SuccinctBitVector().
size()
size_t pfc::succinct::SuccinctBitVector::size () const inline noexcept
Definition at line 269 of file succinct.hpp.
test()
bool pfc::succinct::SuccinctBitVector::test (size_t pos) const inline
Definition at line 280 of file succinct.hpp.
words()
std::span< const uint64_t > pfc::succinct::SuccinctBitVector::words () const inline noexcept
Definition at line 320 of file succinct.hpp.
The documentation for this class was generated from the following file:
pfc/succinct.hpp