PFC - Prefix-Free Codecs: pfc::PackedVector< Element, LengthCodec > Class Template Reference
pfc::PackedVector< Element, LengthCodec > Class Template Reference
#include <pfc/packed.hpp>
Public Types
using value_type = std::vector< typename Element::value_type >
using element_type = Element
using size_type = size_t
Public Member Functions
PackedVector ()=default
PackedVector (size_type count)
PackedVector (const value_type &vals)
size_type size () const noexcept
bool empty () const noexcept
void reserve (size_type new_cap)
void clear () noexcept
const Element & operator[] (size_type pos) const
Element & operator[] (size_type pos)
void push_back (const Element &elem)
void push_back (Element &&elem)
template<typename... Args>
void emplace_back (Args &&... args)
auto begin () noexcept
auto end () noexcept
auto begin () const noexcept
auto end () const noexcept
value_type value () const
Static Public Member Functions
template<typename Sink >
requires BitSink<Sink>
static void encode (const PackedVector &p, Sink &sink)
template<typename Source >
requires BitSource<Source>
static PackedVector decode (Source &source)
Detailed Description
template<PackedValue Element, typename LengthCodec = codecs::EliasGamma>
class pfc::PackedVector< Element, LengthCodec >
Definition at line 274 of file packed.hpp.
Member Typedef Documentation
element_type
template<PackedValue Element, typename LengthCodec = codecs::EliasGamma> using pfc::PackedVector< Element, LengthCodec >::element_type = Element
Definition at line 277 of file packed.hpp.
size_type
template<PackedValue Element, typename LengthCodec = codecs::EliasGamma> using pfc::PackedVector< Element, LengthCodec >::size_type = size_t
Definition at line 278 of file packed.hpp.
value_type
template<PackedValue Element, typename LengthCodec = codecs::EliasGamma> using pfc::PackedVector< Element, LengthCodec >::value_type = std::vector<typename Element::value_type>
Definition at line 276 of file packed.hpp.
Constructor & Destructor Documentation
PackedVector() [1/3]
template<PackedValue Element, typename LengthCodec = codecs::EliasGamma> pfc::PackedVector< Element, LengthCodec >::PackedVector () default
PackedVector() [2/3]
template<PackedValue Element, typename LengthCodec = codecs::EliasGamma> pfc::PackedVector< Element, LengthCodec >::PackedVector (size_type count) inline explicit
Definition at line 287 of file packed.hpp.
PackedVector() [3/3]
template<PackedValue Element, typename LengthCodec = codecs::EliasGamma> pfc::PackedVector< Element, LengthCodec >::PackedVector (const value_type & vals) inline explicit
Definition at line 289 of file packed.hpp.
Member Function Documentation
begin() [1/2]
template<PackedValue Element, typename LengthCodec = codecs::EliasGamma> auto pfc::PackedVector< Element, LengthCodec >::begin () const inline noexcept
Definition at line 329 of file packed.hpp.
begin() [2/2]
template<PackedValue Element, typename LengthCodec = codecs::EliasGamma> auto pfc::PackedVector< Element, LengthCodec >::begin () inline noexcept
Definition at line 327 of file packed.hpp.
clear()
template<PackedValue Element, typename LengthCodec = codecs::EliasGamma> void pfc::PackedVector< Element, LengthCodec >::clear () inline noexcept
Definition at line 301 of file packed.hpp.
decode()
template<PackedValue Element, typename LengthCodec = codecs::EliasGamma> template<typename Source > requires BitSource<Source> static PackedVector pfc::PackedVector< Element, LengthCodec >::decode (Source & source) inline static
Definition at line 352 of file packed.hpp.
References pfc::PackedVector< Element, LengthCodec >::size().
emplace_back()
template<PackedValue Element, typename LengthCodec = codecs::EliasGamma> template<typename... Args> void pfc::PackedVector< Element, LengthCodec >::emplace_back (Args &&... args) inline
Definition at line 322 of file packed.hpp.
empty()
template<PackedValue Element, typename LengthCodec = codecs::EliasGamma> bool pfc::PackedVector< Element, LengthCodec >::empty () const inline noexcept
Definition at line 298 of file packed.hpp.
encode()
template<PackedValue Element, typename LengthCodec = codecs::EliasGamma> template<typename Sink > requires BitSink<Sink> static void pfc::PackedVector< Element, LengthCodec >::encode (const PackedVector< Element, LengthCodec > & p, Sink & sink) inline static
Definition at line 344 of file packed.hpp.
end() [1/2]
template<PackedValue Element, typename LengthCodec = codecs::EliasGamma> auto pfc::PackedVector< Element, LengthCodec >::end () const inline noexcept
Definition at line 330 of file packed.hpp.
end() [2/2]
template<PackedValue Element, typename LengthCodec = codecs::EliasGamma> auto pfc::PackedVector< Element, LengthCodec >::end () inline noexcept
Definition at line 328 of file packed.hpp.
operator[]() [1/2]
template<PackedValue Element, typename LengthCodec = codecs::EliasGamma> Element & pfc::PackedVector< Element, LengthCodec >::operator[] (size_type pos) inline
Definition at line 308 of file packed.hpp.
operator[]() [2/2]
template<PackedValue Element, typename LengthCodec = codecs::EliasGamma> const Element & pfc::PackedVector< Element, LengthCodec >::operator[] (size_type pos) const inline
Definition at line 304 of file packed.hpp.
push_back() [1/2]
template<PackedValue Element, typename LengthCodec = codecs::EliasGamma> void pfc::PackedVector< Element, LengthCodec >::push_back (const Element & elem) inline
Definition at line 313 of file packed.hpp.
push_back() [2/2]
template<PackedValue Element, typename LengthCodec = codecs::EliasGamma> void pfc::PackedVector< Element, LengthCodec >::push_back (Element && elem) inline
Definition at line 317 of file packed.hpp.
reserve()
template<PackedValue Element, typename LengthCodec = codecs::EliasGamma> void pfc::PackedVector< Element, LengthCodec >::reserve (size_type new_cap) inline
Definition at line 300 of file packed.hpp.
size()
template<PackedValue Element, typename LengthCodec = codecs::EliasGamma> size_type pfc::PackedVector< Element, LengthCodec >::size () const inline noexcept
Definition at line 297 of file packed.hpp.
Referenced by pfc::PackedVector< Element, LengthCodec >::decode(), and pfc::PackedVector< Element, LengthCodec >::value().
value()
template<PackedValue Element, typename LengthCodec = codecs::EliasGamma> value_type pfc::PackedVector< Element, LengthCodec >::value () const inline
Definition at line 333 of file packed.hpp.
References pfc::PackedVector< Element, LengthCodec >::size().
The documentation for this class was generated from the following file:
pfc/packed.hpp