PFC - Prefix-Free Codecs: pfc::PackedVec< N, Component > Class Template Reference
pfc::PackedVec< N, Component > Class Template Reference
#include <pfc/coordinates.hpp>
Public Types
using value_type = std::array< typename Component::value_type, N >
using component_type = Component
using scalar_type = typename Component::value_type
Public Member Functions
PackedVec ()=default
PackedVec (const value_type &values)
template<typename... Args>
requires (sizeof...(Args) == N)
PackedVec (Args... args)
const Component & operator[] (size_t i) const
Component & operator[] (size_t i)
value_type value () const
PackedVec operator+ (const PackedVec &other) const
PackedVec & operator+= (const PackedVec &other)
PackedVec operator- (const PackedVec &other) const
PackedVec & operator-= (const PackedVec &other)
PackedVec operator- () const
PackedVec operator* (scalar_type s) const
PackedVec & operator*= (scalar_type s)
PackedVec operator/ (scalar_type s) const
PackedVec & operator/= (scalar_type s)
scalar_type dot (const PackedVec &other) const
scalar_type magnitude () const
scalar_type magnitude_squared () const
PackedVec normalized () const
PackedVec cross (const PackedVec &other) const
bool operator== (const PackedVec &other) const
Static Public Member Functions
template<typename Sink >
requires BitSink<Sink>
static void encode (const PackedVec &v, Sink &sink)
template<typename Source >
requires BitSource<Source>
static PackedVec decode (Source &source)
Static Public Attributes
static constexpr size_t dimensions = N
Friends
PackedVec operator* (scalar_type s, const PackedVec &v)
Detailed Description
template<size_t N, PackedValue Component = Packed<double, codecs::Float32>>
class pfc::PackedVec< N, Component >
Definition at line 126 of file coordinates.hpp.
Member Typedef Documentation
component_type
template<size_t N, PackedValue Component = Packed<double, codecs::Float32>> using pfc::PackedVec< N, Component >::component_type = Component
Definition at line 129 of file coordinates.hpp.
scalar_type
template<size_t N, PackedValue Component = Packed<double, codecs::Float32>> using pfc::PackedVec< N, Component >::scalar_type = typename Component::value_type
Definition at line 130 of file coordinates.hpp.
value_type
template<size_t N, PackedValue Component = Packed<double, codecs::Float32>> using pfc::PackedVec< N, Component >::value_type = std::array<typename Component::value_type, N>
Definition at line 128 of file coordinates.hpp.
Constructor & Destructor Documentation
PackedVec() [1/3]
template<size_t N, PackedValue Component = Packed<double, codecs::Float32>> pfc::PackedVec< N, Component >::PackedVec () default
PackedVec() [2/3]
template<size_t N, PackedValue Component = Packed<double, codecs::Float32>> pfc::PackedVec< N, Component >::PackedVec (const value_type & values) inline explicit
Definition at line 140 of file coordinates.hpp.
PackedVec() [3/3]
template<size_t N, PackedValue Component = Packed<double, codecs::Float32>> template<typename... Args> requires (sizeof...(Args) == N) pfc::PackedVec< N, Component >::PackedVec (Args... args) inline explicit
Definition at line 147 of file coordinates.hpp.
Member Function Documentation
cross()
template<size_t N, PackedValue Component = Packed<double, codecs::Float32>> PackedVec pfc::PackedVec< N, Component >::cross (const PackedVec< N, Component > & other) const inline
Definition at line 268 of file coordinates.hpp.
References pfc::PackedVec< N, Component >::value().
decode()
template<size_t N, PackedValue Component = Packed<double, codecs::Float32>> template<typename Source > requires BitSource<Source> static PackedVec pfc::PackedVec< N, Component >::decode (Source & source) inline static
Definition at line 297 of file coordinates.hpp.
Referenced by pfc::PackedAffineTransform< N, Scalar >::decode().
dot()
template<size_t N, PackedValue Component = Packed<double, codecs::Float32>> scalar_type pfc::PackedVec< N, Component >::dot (const PackedVec< N, Component > & other) const inline
Definition at line 243 of file coordinates.hpp.
References pfc::result< T >::value().
Referenced by pfc::PackedVec< N, Component >::magnitude(), and pfc::PackedVec< N, Component >::magnitude_squared().
encode()
template<size_t N, PackedValue Component = Packed<double, codecs::Float32>> template<typename Sink > requires BitSink<Sink> static void pfc::PackedVec< N, Component >::encode (const PackedVec< N, Component > & v, Sink & sink) inline static
Definition at line 290 of file coordinates.hpp.
Referenced by pfc::PackedAffineTransform< N, Scalar >::encode().
magnitude()
template<size_t N, PackedValue Component = Packed<double, codecs::Float32>> scalar_type pfc::PackedVec< N, Component >::magnitude () const inline
Definition at line 252 of file coordinates.hpp.
References pfc::PackedVec< N, Component >::dot().
Referenced by pfc::PackedVec< N, Component >::normalized().
magnitude_squared()
template<size_t N, PackedValue Component = Packed<double, codecs::Float32>> scalar_type pfc::PackedVec< N, Component >::magnitude_squared () const inline
Definition at line 256 of file coordinates.hpp.
References pfc::PackedVec< N, Component >::dot().
normalized()
template<size_t N, PackedValue Component = Packed<double, codecs::Float32>> PackedVec pfc::PackedVec< N, Component >::normalized () const inline
Definition at line 261 of file coordinates.hpp.
References pfc::PackedVec< N, Component >::magnitude().
operator*()
template<size_t N, PackedValue Component = Packed<double, codecs::Float32>> PackedVec pfc::PackedVec< N, Component >::operator* (scalar_type s) const inline
Definition at line 207 of file coordinates.hpp.
References pfc::result< T >::value().
operator*=()
template<size_t N, PackedValue Component = Packed<double, codecs::Float32>> PackedVec & pfc::PackedVec< N, Component >::operator*= (scalar_type s) inline
Definition at line 219 of file coordinates.hpp.
References pfc::PackedVec< N, Component >::value().
operator+()
template<size_t N, PackedValue Component = Packed<double, codecs::Float32>> PackedVec pfc::PackedVec< N, Component >::operator+ (const PackedVec< N, Component > & other) const inline
Definition at line 166 of file coordinates.hpp.
References pfc::result< T >::value().
operator+=()
template<size_t N, PackedValue Component = Packed<double, codecs::Float32>> PackedVec & pfc::PackedVec< N, Component >::operator+= (const PackedVec< N, Component > & other) inline
Definition at line 174 of file coordinates.hpp.
References pfc::PackedVec< N, Component >::value().
operator-() [1/2]
template<size_t N, PackedValue Component = Packed<double, codecs::Float32>> PackedVec pfc::PackedVec< N, Component >::operator- () const inline
Definition at line 198 of file coordinates.hpp.
References pfc::result< T >::value().
operator-() [2/2]
template<size_t N, PackedValue Component = Packed<double, codecs::Float32>> PackedVec pfc::PackedVec< N, Component >::operator- (const PackedVec< N, Component > & other) const inline
Definition at line 182 of file coordinates.hpp.
References pfc::result< T >::value().
operator-=()
template<size_t N, PackedValue Component = Packed<double, codecs::Float32>> PackedVec & pfc::PackedVec< N, Component >::operator-= (const PackedVec< N, Component > & other) inline
Definition at line 190 of file coordinates.hpp.
References pfc::PackedVec< N, Component >::value().
operator/()
template<size_t N, PackedValue Component = Packed<double, codecs::Float32>> PackedVec pfc::PackedVec< N, Component >::operator/ (scalar_type s) const inline
Definition at line 227 of file coordinates.hpp.
References pfc::result< T >::value().
operator/=()
template<size_t N, PackedValue Component = Packed<double, codecs::Float32>> PackedVec & pfc::PackedVec< N, Component >::operator/= (scalar_type s) inline
Definition at line 235 of file coordinates.hpp.
References pfc::PackedVec< N, Component >::value().
operator==()
template<size_t N, PackedValue Component = Packed<double, codecs::Float32>> bool pfc::PackedVec< N, Component >::operator== (const PackedVec< N, Component > & other) const inline
Definition at line 279 of file coordinates.hpp.
References pfc::PackedVec< N, Component >::value().
operator[]() [1/2]
template<size_t N, PackedValue Component = Packed<double, codecs::Float32>> Component & pfc::PackedVec< N, Component >::operator[] (size_t i) inline
Definition at line 154 of file coordinates.hpp.
operator[]() [2/2]
template<size_t N, PackedValue Component = Packed<double, codecs::Float32>> const Component & pfc::PackedVec< N, Component >::operator[] (size_t i) const inline
Definition at line 153 of file coordinates.hpp.
value()
template<size_t N, PackedValue Component = Packed<double, codecs::Float32>> value_type pfc::PackedVec< N, Component >::value () const inline
Definition at line 157 of file coordinates.hpp.
References pfc::result< T >::value().
Referenced by pfc::PackedVec< N, Component >::cross(), pfc::PackedVec< N, Component >::operator*=(), pfc::PackedVec< N, Component >::operator+=(), pfc::PackedVec< N, Component >::operator-=(), pfc::PackedVec< N, Component >::operator/=(), and pfc::PackedVec< N, Component >::operator==().
Friends And Related Symbol Documentation
operator*
template<size_t N, PackedValue Component = Packed<double, codecs::Float32>> PackedVec operator* (scalar_type s, const PackedVec< N, Component > & v) friend
Definition at line 215 of file coordinates.hpp.
Member Data Documentation
dimensions
template<size_t N, PackedValue Component = Packed<double, codecs::Float32>> constexpr size_t pfc::PackedVec< N, Component >::dimensions = N static constexpr
Definition at line 131 of file coordinates.hpp.
The documentation for this class was generated from the following file:
pfc/coordinates.hpp