PFC - Prefix-Free Codecs: pfc::PackedIterator< Element, Container > Class Template Reference
pfc::PackedIterator< Element, Container > Class Template Reference
#include <pfc/stl_integration.hpp>
Public Types
using iterator_category = std::random_access_iterator_tag
using value_type = typename Element::value_type
using difference_type = std::ptrdiff_t
using pointer = void
using reference = PackedProxy< Element, Container >
Public Member Functions
PackedIterator ()
PackedIterator (Container *c, size_t i)
reference operator* () const
PackedIterator & operator++ ()
PackedIterator operator++ (int)
PackedIterator & operator-- ()
PackedIterator operator-- (int)
PackedIterator & operator+= (difference_type n)
PackedIterator & operator-= (difference_type n)
PackedIterator operator+ (difference_type n) const
PackedIterator operator- (difference_type n) const
difference_type operator- (const PackedIterator &other) const
bool operator== (const PackedIterator &other) const
bool operator!= (const PackedIterator &other) const
bool operator< (const PackedIterator &other) const
bool operator> (const PackedIterator &other) const
bool operator<= (const PackedIterator &other) const
bool operator>= (const PackedIterator &other) const
reference operator[] (difference_type n) const
Detailed Description
template<typename Element, typename Container>
class pfc::PackedIterator< Element, Container >
Definition at line 77 of file stl_integration.hpp.
Member Typedef Documentation
difference_type
template<typename Element , typename Container > using pfc::PackedIterator< Element, Container >::difference_type = std::ptrdiff_t
Definition at line 81 of file stl_integration.hpp.
iterator_category
template<typename Element , typename Container > using pfc::PackedIterator< Element, Container >::iterator_category = std::random_access_iterator_tag
Definition at line 79 of file stl_integration.hpp.
pointer
template<typename Element , typename Container > using pfc::PackedIterator< Element, Container >::pointer = void
Definition at line 82 of file stl_integration.hpp.
reference
template<typename Element , typename Container > using pfc::PackedIterator< Element, Container >::reference = PackedProxy<Element, Container>
Definition at line 83 of file stl_integration.hpp.
value_type
template<typename Element , typename Container > using pfc::PackedIterator< Element, Container >::value_type = typename Element::value_type
Definition at line 80 of file stl_integration.hpp.
Constructor & Destructor Documentation
PackedIterator() [1/2]
template<typename Element , typename Container > pfc::PackedIterator< Element, Container >::PackedIterator () inline
Definition at line 90 of file stl_integration.hpp.
Referenced by pfc::PackedIterator< Element, Container >::operator+(), and pfc::PackedIterator< Element, Container >::operator-().
PackedIterator() [2/2]
template<typename Element , typename Container > pfc::PackedIterator< Element, Container >::PackedIterator (Container * c, size_t i) inline
Definition at line 91 of file stl_integration.hpp.
Member Function Documentation
operator!=()
template<typename Element , typename Container > bool pfc::PackedIterator< Element, Container >::operator!= (const PackedIterator< Element, Container > & other) const inline
Definition at line 149 of file stl_integration.hpp.
operator*()
template<typename Element , typename Container > reference pfc::PackedIterator< Element, Container >::operator* () const inline
Definition at line 94 of file stl_integration.hpp.
operator+()
template<typename Element , typename Container > PackedIterator pfc::PackedIterator< Element, Container >::operator+ (difference_type n) const inline
Definition at line 132 of file stl_integration.hpp.
References pfc::PackedIterator< Element, Container >::PackedIterator().
operator++() [1/2]
template<typename Element , typename Container > PackedIterator & pfc::PackedIterator< Element, Container >::operator++ () inline
Definition at line 99 of file stl_integration.hpp.
operator++() [2/2]
template<typename Element , typename Container > PackedIterator pfc::PackedIterator< Element, Container >::operator++ (int) inline
Definition at line 104 of file stl_integration.hpp.
operator+=()
template<typename Element , typename Container > PackedIterator & pfc::PackedIterator< Element, Container >::operator+= (difference_type n) inline
Definition at line 122 of file stl_integration.hpp.
operator-() [1/2]
template<typename Element , typename Container > difference_type pfc::PackedIterator< Element, Container >::operator- (const PackedIterator< Element, Container > & other) const inline
Definition at line 140 of file stl_integration.hpp.
operator-() [2/2]
template<typename Element , typename Container > PackedIterator pfc::PackedIterator< Element, Container >::operator- (difference_type n) const inline
Definition at line 136 of file stl_integration.hpp.
References pfc::PackedIterator< Element, Container >::PackedIterator().
operator--() [1/2]
template<typename Element , typename Container > PackedIterator & pfc::PackedIterator< Element, Container >::operator-- () inline
Definition at line 110 of file stl_integration.hpp.
operator--() [2/2]
template<typename Element , typename Container > PackedIterator pfc::PackedIterator< Element, Container >::operator-- (int) inline
Definition at line 115 of file stl_integration.hpp.
operator-=()
template<typename Element , typename Container > PackedIterator & pfc::PackedIterator< Element, Container >::operator-= (difference_type n) inline
Definition at line 127 of file stl_integration.hpp.
operator<()
template<typename Element , typename Container > bool pfc::PackedIterator< Element, Container >::operator< (const PackedIterator< Element, Container > & other) const inline
Definition at line 153 of file stl_integration.hpp.
operator<=()
template<typename Element , typename Container > bool pfc::PackedIterator< Element, Container >::operator<= (const PackedIterator< Element, Container > & other) const inline
Definition at line 161 of file stl_integration.hpp.
operator==()
template<typename Element , typename Container > bool pfc::PackedIterator< Element, Container >::operator== (const PackedIterator< Element, Container > & other) const inline
Definition at line 145 of file stl_integration.hpp.
operator>()
template<typename Element , typename Container > bool pfc::PackedIterator< Element, Container >::operator> (const PackedIterator< Element, Container > & other) const inline
Definition at line 157 of file stl_integration.hpp.
operator>=()
template<typename Element , typename Container > bool pfc::PackedIterator< Element, Container >::operator>= (const PackedIterator< Element, Container > & other) const inline
Definition at line 165 of file stl_integration.hpp.
operator[]()
template<typename Element , typename Container > reference pfc::PackedIterator< Element, Container >::operator[] (difference_type n) const inline
Definition at line 170 of file stl_integration.hpp.
The documentation for this class was generated from the following file:
pfc/stl_integration.hpp