PFC - Prefix-Free Codecs: pfc::PackedMatrix< Rows, Cols, Element > Class Template Reference
pfc::PackedMatrix< Rows, Cols, Element > Class Template Reference
#include <pfc/coordinates.hpp>
Public Types
using value_type = std::array< std::array< typename Element::value_type, Cols >, Rows >
using element_type = Element
using scalar_type = typename Element::value_type
Public Member Functions
PackedMatrix ()=default
PackedMatrix (const value_type &values)
const Element & operator() (size_t i, size_t j) const
Element & operator() (size_t i, size_t j)
PackedVec< Cols, Element > row (size_t i) const
PackedVec< Rows, Element > column (size_t j) const
value_type value () const
PackedMatrix operator+ (const PackedMatrix &other) const
PackedMatrix operator- (const PackedMatrix &other) const
PackedMatrix operator* (scalar_type s) const
PackedVec< Rows, Element > operator* (const PackedVec< Cols, Element > &v) const
template<size_t OtherCols>
PackedMatrix< Rows, OtherCols, Element > operator* (const PackedMatrix< Cols, OtherCols, Element > &other) const
PackedMatrix< Cols, Rows, Element > transpose () const
scalar_type determinant () const
scalar_type determinant () const
Static Public Member Functions
static PackedMatrix identity ()
template<typename Sink >
requires BitSink<Sink>
static void encode (const PackedMatrix &m, Sink &sink)
template<typename Source >
requires BitSource<Source>
static PackedMatrix decode (Source &source)
Static Public Attributes
static constexpr size_t rows = Rows
static constexpr size_t cols = Cols
Detailed Description
template<size_t Rows, size_t Cols, PackedValue Element = Packed<double, codecs::Float32>>
class pfc::PackedMatrix< Rows, Cols, Element >
Definition at line 317 of file coordinates.hpp.
Member Typedef Documentation
element_type
template<size_t Rows, size_t Cols, PackedValue Element = Packed<double, codecs::Float32>> using pfc::PackedMatrix< Rows, Cols, Element >::element_type = Element
Definition at line 320 of file coordinates.hpp.
scalar_type
template<size_t Rows, size_t Cols, PackedValue Element = Packed<double, codecs::Float32>> using pfc::PackedMatrix< Rows, Cols, Element >::scalar_type = typename Element::value_type
Definition at line 321 of file coordinates.hpp.
value_type
template<size_t Rows, size_t Cols, PackedValue Element = Packed<double, codecs::Float32>> using pfc::PackedMatrix< Rows, Cols, Element >::value_type = std::array<std::array<typename Element::value_type, Cols>, Rows>
Definition at line 319 of file coordinates.hpp.
Constructor & Destructor Documentation
PackedMatrix() [1/2]
template<size_t Rows, size_t Cols, PackedValue Element = Packed<double, codecs::Float32>> pfc::PackedMatrix< Rows, Cols, Element >::PackedMatrix () default
PackedMatrix() [2/2]
template<size_t Rows, size_t Cols, PackedValue Element = Packed<double, codecs::Float32>> pfc::PackedMatrix< Rows, Cols, Element >::PackedMatrix (const value_type & values) inline explicit
Definition at line 332 of file coordinates.hpp.
Member Function Documentation
column()
template<size_t Rows, size_t Cols, PackedValue Element = Packed<double, codecs::Float32>> PackedVec< Rows, Element > pfc::PackedMatrix< Rows, Cols, Element >::column (size_t j) const inline
Definition at line 359 of file coordinates.hpp.
decode()
template<size_t Rows, size_t Cols, PackedValue Element = Packed<double, codecs::Float32>> template<typename Source > requires BitSource<Source> static PackedMatrix pfc::PackedMatrix< Rows, Cols, Element >::decode (Source & source) inline static
Definition at line 485 of file coordinates.hpp.
References pfc::PackedMatrix< Rows, Cols, Element >::row().
Referenced by pfc::PackedAffineTransform< N, Scalar >::decode().
determinant() [1/2]
template<size_t Rows, size_t Cols, PackedValue Element = Packed<double, codecs::Float32>> scalar_type pfc::PackedMatrix< Rows, Cols, Element >::determinant () const inline
Definition at line 462 of file coordinates.hpp.
References pfc::PackedMatrix< Rows, Cols, Element >::value().
determinant() [2/2]
template<size_t Rows, size_t Cols, PackedValue Element = Packed<double, codecs::Float32>> scalar_type pfc::PackedMatrix< Rows, Cols, Element >::determinant () const inline
Definition at line 467 of file coordinates.hpp.
References pfc::PackedMatrix< Rows, Cols, Element >::value().
encode()
template<size_t Rows, size_t Cols, PackedValue Element = Packed<double, codecs::Float32>> template<typename Sink > requires BitSink<Sink> static void pfc::PackedMatrix< Rows, Cols, Element >::encode (const PackedMatrix< Rows, Cols, Element > & m, Sink & sink) inline static
Definition at line 476 of file coordinates.hpp.
References pfc::PackedMatrix< Rows, Cols, Element >::row().
Referenced by pfc::PackedAffineTransform< N, Scalar >::encode().
identity()
template<size_t Rows, size_t Cols, PackedValue Element = Packed<double, codecs::Float32>> static PackedMatrix pfc::PackedMatrix< Rows, Cols, Element >::identity () inline static
Definition at line 453 of file coordinates.hpp.
Referenced by pfc::PackedAffineTransform< N, Scalar >::scale(), and pfc::PackedAffineTransform< N, Scalar >::translation().
operator()() [1/2]
template<size_t Rows, size_t Cols, PackedValue Element = Packed<double, codecs::Float32>> Element & pfc::PackedMatrix< Rows, Cols, Element >::operator() (size_t i, size_t j) inline
Definition at line 345 of file coordinates.hpp.
operator()() [2/2]
template<size_t Rows, size_t Cols, PackedValue Element = Packed<double, codecs::Float32>> const Element & pfc::PackedMatrix< Rows, Cols, Element >::operator() (size_t i, size_t j) const inline
Definition at line 341 of file coordinates.hpp.
operator*() [1/3]
template<size_t Rows, size_t Cols, PackedValue Element = Packed<double, codecs::Float32>> template<size_t OtherCols> PackedMatrix< Rows, OtherCols, Element > pfc::PackedMatrix< Rows, Cols, Element >::operator* (const PackedMatrix< Cols, OtherCols, Element > & other) const inline
Definition at line 422 of file coordinates.hpp.
References pfc::result< T >::value(), and pfc::PackedMatrix< Rows, Cols, Element >::value().
operator*() [2/3]
template<size_t Rows, size_t Cols, PackedValue Element = Packed<double, codecs::Float32>> PackedVec< Rows, Element > pfc::PackedMatrix< Rows, Cols, Element >::operator* (const PackedVec< Cols, Element > & v) const inline
Definition at line 412 of file coordinates.hpp.
References pfc::PackedMatrix< Rows, Cols, Element >::row().
operator*() [3/3]
template<size_t Rows, size_t Cols, PackedValue Element = Packed<double, codecs::Float32>> PackedMatrix pfc::PackedMatrix< Rows, Cols, Element >::operator* (scalar_type s) const inline
Definition at line 401 of file coordinates.hpp.
References pfc::result< T >::value().
operator+()
template<size_t Rows, size_t Cols, PackedValue Element = Packed<double, codecs::Float32>> PackedMatrix pfc::PackedMatrix< Rows, Cols, Element >::operator+ (const PackedMatrix< Rows, Cols, Element > & other) const inline
Definition at line 379 of file coordinates.hpp.
References pfc::result< T >::value().
operator-()
template<size_t Rows, size_t Cols, PackedValue Element = Packed<double, codecs::Float32>> PackedMatrix pfc::PackedMatrix< Rows, Cols, Element >::operator- (const PackedMatrix< Rows, Cols, Element > & other) const inline
Definition at line 390 of file coordinates.hpp.
References pfc::result< T >::value().
row()
template<size_t Rows, size_t Cols, PackedValue Element = Packed<double, codecs::Float32>> PackedVec< Cols, Element > pfc::PackedMatrix< Rows, Cols, Element >::row (size_t i) const inline
Definition at line 350 of file coordinates.hpp.
Referenced by pfc::PackedMatrix< Rows, Cols, Element >::decode(), pfc::PackedMatrix< Rows, Cols, Element >::encode(), and pfc::PackedMatrix< Rows, Cols, Element >::operator*().
transpose()
template<size_t Rows, size_t Cols, PackedValue Element = Packed<double, codecs::Float32>> PackedMatrix< Cols, Rows, Element > pfc::PackedMatrix< Rows, Cols, Element >::transpose () const inline
Definition at line 442 of file coordinates.hpp.
References pfc::result< T >::value().
value()
template<size_t Rows, size_t Cols, PackedValue Element = Packed<double, codecs::Float32>> value_type pfc::PackedMatrix< Rows, Cols, Element >::value () const inline
Definition at line 368 of file coordinates.hpp.
References pfc::result< T >::value().
Referenced by pfc::PackedMatrix< Rows, Cols, Element >::determinant(), and pfc::PackedMatrix< Rows, Cols, Element >::operator*().
Member Data Documentation
cols
template<size_t Rows, size_t Cols, PackedValue Element = Packed<double, codecs::Float32>> constexpr size_t pfc::PackedMatrix< Rows, Cols, Element >::cols = Cols static constexpr
Definition at line 323 of file coordinates.hpp.
rows
template<size_t Rows, size_t Cols, PackedValue Element = Packed<double, codecs::Float32>> constexpr size_t pfc::PackedMatrix< Rows, Cols, Element >::rows = Rows static constexpr
Definition at line 322 of file coordinates.hpp.
The documentation for this class was generated from the following file:
pfc/coordinates.hpp