PFC - Prefix-Free Codecs: pfc::succinct::RoaringBitmap Class Reference
pfc::succinct::RoaringBitmap Class Reference
#include <pfc/succinct.hpp>
Classes
class iterator
struct Stats
Public Types
using value_type = uint32_t
using size_type = size_t
Public Member Functions
RoaringBitmap ()=default
RoaringBitmap (std::initializer_list< uint32_t > values)
template<typename Iterator >
RoaringBitmap (Iterator begin, Iterator end)
bool contains (uint32_t x) const
void insert (uint32_t x)
void remove (uint32_t x)
size_t cardinality () const
size_t size () const
bool empty () const
void clear ()
void optimize ()
iterator begin () const
iterator end () const
RoaringBitmap union_with (const RoaringBitmap &other) const
RoaringBitmap intersect_with (const RoaringBitmap &other) const
RoaringBitmap difference (const RoaringBitmap &other) const
RoaringBitmap operator| (const RoaringBitmap &other) const
RoaringBitmap operator& (const RoaringBitmap &other) const
RoaringBitmap operator- (const RoaringBitmap &other) const
Stats stats () const
Static Public Member Functions
template<typename Sink >
requires BitSink<Sink>
static void encode (const RoaringBitmap &rb, Sink &sink)
template<typename Source >
requires BitSource<Source>
static RoaringBitmap decode (Source &source)
Detailed Description
Definition at line 376 of file succinct.hpp.
Member Typedef Documentation
size_type
using pfc::succinct::RoaringBitmap::size_type = size_t
Definition at line 379 of file succinct.hpp.
value_type
using pfc::succinct::RoaringBitmap::value_type = uint32_t
Definition at line 378 of file succinct.hpp.
Constructor & Destructor Documentation
RoaringBitmap() [1/3]
pfc::succinct::RoaringBitmap::RoaringBitmap () default
RoaringBitmap() [2/3]
pfc::succinct::RoaringBitmap::RoaringBitmap (std::initializer_list< uint32_t > values) inline
Definition at line 643 of file succinct.hpp.
References insert(), and optimize().
RoaringBitmap() [3/3]
template<typename Iterator > pfc::succinct::RoaringBitmap::RoaringBitmap (Iterator begin, Iterator end) inline
Definition at line 652 of file succinct.hpp.
References begin(), end(), insert(), and optimize().
Member Function Documentation
begin()
iterator pfc::succinct::RoaringBitmap::begin () const inline
Definition at line 848 of file succinct.hpp.
Referenced by RoaringBitmap().
cardinality()
size_t pfc::succinct::RoaringBitmap::cardinality () const inline
Definition at line 695 of file succinct.hpp.
Referenced by size().
clear()
void pfc::succinct::RoaringBitmap::clear () inline
Definition at line 709 of file succinct.hpp.
contains()
bool pfc::succinct::RoaringBitmap::contains (uint32_t x) const inline
Definition at line 661 of file succinct.hpp.
decode()
template<typename Source > requires BitSource<Source> static RoaringBitmap pfc::succinct::RoaringBitmap::decode (Source & source) inline static
Definition at line 1058 of file succinct.hpp.
References size().
difference()
RoaringBitmap pfc::succinct::RoaringBitmap::difference (const RoaringBitmap & other) const inline
Definition at line 961 of file succinct.hpp.
Referenced by operator-().
empty()
bool pfc::succinct::RoaringBitmap::empty () const inline
Definition at line 705 of file succinct.hpp.
encode()
template<typename Sink > requires BitSink<Sink> static void pfc::succinct::RoaringBitmap::encode (const RoaringBitmap & rb, Sink & sink) inline static
Definition at line 1021 of file succinct.hpp.
References pfc::codecs::Fixed< Width >::encode(), and pfc::codecs::EliasGamma::encode().
end()
iterator pfc::succinct::RoaringBitmap::end () const inline
Definition at line 849 of file succinct.hpp.
Referenced by pfc::succinct::RoaringBitmap::iterator::iterator(), and RoaringBitmap().
insert()
void pfc::succinct::RoaringBitmap::insert (uint32_t x) inline
Definition at line 669 of file succinct.hpp.
Referenced by RoaringBitmap(), and RoaringBitmap().
intersect_with()
RoaringBitmap pfc::succinct::RoaringBitmap::intersect_with (const RoaringBitmap & other) const inline
Definition at line 911 of file succinct.hpp.
Referenced by operator&().
operator&()
RoaringBitmap pfc::succinct::RoaringBitmap::operator& (const RoaringBitmap & other) const inline
Definition at line 1015 of file succinct.hpp.
References intersect_with().
operator-()
RoaringBitmap pfc::succinct::RoaringBitmap::operator- (const RoaringBitmap & other) const inline
Definition at line 1016 of file succinct.hpp.
References difference().
operator|()
RoaringBitmap pfc::succinct::RoaringBitmap::operator| (const RoaringBitmap & other) const inline
Definition at line 1014 of file succinct.hpp.
References union_with().
optimize()
void pfc::succinct::RoaringBitmap::optimize () inline
Definition at line 714 of file succinct.hpp.
Referenced by RoaringBitmap(), and RoaringBitmap().
remove()
void pfc::succinct::RoaringBitmap::remove (uint32_t x) inline
Definition at line 677 of file succinct.hpp.
size()
size_t pfc::succinct::RoaringBitmap::size () const inline
Definition at line 703 of file succinct.hpp.
References cardinality().
Referenced by decode().
stats()
Stats pfc::succinct::RoaringBitmap::stats () const inline
Definition at line 1115 of file succinct.hpp.
References pfc::succinct::RoaringBitmap::Stats::num_chunks.
union_with()
RoaringBitmap pfc::succinct::RoaringBitmap::union_with (const RoaringBitmap & other) const inline
Definition at line 853 of file succinct.hpp.
Referenced by operator|().
The documentation for this class was generated from the following file:
pfc/succinct.hpp