PFC - Prefix-Free Codecs: pfc::result< T > Class Template Reference
pfc::result< T > Class Template Reference
#include <pfc/error_handling.hpp>
Public Member Functions
result (T value)
result (std::error_code ec)
bool has_value () const
operator bool () const
T & value ()
const T & value () const
T & operator* ()
const T & operator* () const
T * operator-> ()
const T * operator-> () const
std::error_code error () const
Detailed Description
template<typename T>
class pfc::result< T >
Definition at line 116 of file error_handling.hpp.
Constructor & Destructor Documentation
result() [1/2]
template<typename T > pfc::result< T >::result (T value) inline
Definition at line 118 of file error_handling.hpp.
result() [2/2]
template<typename T > pfc::result< T >::result (std::error_code ec) inline
Definition at line 119 of file error_handling.hpp.
Member Function Documentation
error()
template<typename T > std::error_code pfc::result< T >::error () const inline
Definition at line 139 of file error_handling.hpp.
References pfc::result< T >::has_value().
Referenced by pfc::result< T >::value(), pfc::result< T >::value(), and pfc::result< void >::value().
has_value()
template<typename T > bool pfc::result< T >::has_value () const inline
Definition at line 121 of file error_handling.hpp.
Referenced by pfc::result< T >::error(), pfc::result< T >::operator bool(), pfc::result< void >::operator bool(), pfc::result< T >::value(), pfc::result< T >::value(), and pfc::result< void >::value().
operator bool()
template<typename T > pfc::result< T >::operator bool () const inline explicit
Definition at line 122 of file error_handling.hpp.
References pfc::result< T >::has_value().
operator*() [1/2]
template<typename T > T & pfc::result< T >::operator* () inline
Definition at line 134 of file error_handling.hpp.
References pfc::result< T >::value().
operator*() [2/2]
template<typename T > const T & pfc::result< T >::operator* () const inline
Definition at line 135 of file error_handling.hpp.
References pfc::result< T >::value().
operator->() [1/2]
template<typename T > T * pfc::result< T >::operator-> () inline
Definition at line 136 of file error_handling.hpp.
References pfc::result< T >::value().
operator->() [2/2]
template<typename T > const T * pfc::result< T >::operator-> () const inline
Definition at line 137 of file error_handling.hpp.
References pfc::result< T >::value().
value() [1/2]
template<typename T > T & pfc::result< T >::value () inline
Definition at line 124 of file error_handling.hpp.
References pfc::result< T >::error(), and pfc::result< T >::has_value().
Referenced by pfc::PackedVec< N, Component >::dot(), pfc::result< T >::operator*(), pfc::result< T >::operator*(), pfc::PackedMatrix< Rows, Cols, Element >::operator*(), pfc::PackedVec< N, Component >::operator*(), pfc::PackedMatrix< Rows, Cols, Element >::operator*(), pfc::PackedMatrix< Rows, Cols, Element >::operator+(), pfc::PackedVec< N, Component >::operator+(), pfc::PackedVec< N, Component >::operator-(), pfc::PackedMatrix< Rows, Cols, Element >::operator-(), pfc::PackedVec< N, Component >::operator-(), pfc::result< T >::operator->(), pfc::result< T >::operator->(), pfc::PackedVec< N, Component >::operator/(), pfc::PackedMatrix< Rows, Cols, Element >::transpose(), pfc::PackedPoint< N, Coordinate >::value(), pfc::PackedVec< N, Component >::value(), and pfc::PackedMatrix< Rows, Cols, Element >::value().
value() [2/2]
template<typename T > const T & pfc::result< T >::value () const inline
Definition at line 129 of file error_handling.hpp.
References pfc::result< T >::error(), and pfc::result< T >::has_value().
The documentation for this class was generated from the following file:
pfc/error_handling.hpp