PFC - Prefix-Free Codecs: pfc::TypeErasedPackedContainer Class Reference
pfc::TypeErasedPackedContainer Class Reference
#include <pfc/stl_integration.hpp>
Public Member Functions
std::type_index stored_type () const
size_t size () const
size_t data_bytes () const
void clear ()
std::any operator[] (size_t index) const
template<typename T >
void push_back (const T &value)
template<typename T >
bool holds_type () const
template<typename T >
std::optional< T > get (size_t index) const
Static Public Member Functions
template<PackedValue Element>
static TypeErasedPackedContainer create ()
Detailed Description
Definition at line 337 of file stl_integration.hpp.
Member Function Documentation
clear()
void pfc::TypeErasedPackedContainer::clear () inline
Definition at line 404 of file stl_integration.hpp.
create()
template<PackedValue Element> static TypeErasedPackedContainer pfc::TypeErasedPackedContainer::create () inline static
Definition at line 384 of file stl_integration.hpp.
data_bytes()
size_t pfc::TypeErasedPackedContainer::data_bytes () const inline
Definition at line 400 of file stl_integration.hpp.
get()
template<typename T > std::optional< T > pfc::TypeErasedPackedContainer::get (size_t index) const inline
Definition at line 427 of file stl_integration.hpp.
References size().
holds_type()
template<typename T > bool pfc::TypeErasedPackedContainer::holds_type () const inline
Definition at line 421 of file stl_integration.hpp.
References stored_type().
operator[]()
std::any pfc::TypeErasedPackedContainer::operator[] (size_t index) const inline
Definition at line 408 of file stl_integration.hpp.
push_back()
template<typename T > void pfc::TypeErasedPackedContainer::push_back (const T & value) inline
Definition at line 413 of file stl_integration.hpp.
size()
size_t pfc::TypeErasedPackedContainer::size () const inline
Definition at line 396 of file stl_integration.hpp.
Referenced by get().
stored_type()
std::type_index pfc::TypeErasedPackedContainer::stored_type () const inline
Definition at line 391 of file stl_integration.hpp.
Referenced by holds_type().
The documentation for this class was generated from the following file:
pfc/stl_integration.hpp