PFC - Prefix-Free Codecs: pfc::BitReader Class Reference
pfc::BitReader Class Reference
#include <pfc/core.hpp>
Public Member Functions
BitReader (const uint8_t *ptr, size_t size) noexcept
BitReader (std::span< const uint8_t > buffer) noexcept
bool peek () const noexcept
bool read () noexcept
uint64_t read_bits (size_t count) noexcept
void align () noexcept
const uint8_t * position () const noexcept
Detailed Description
Definition at line 105 of file core.hpp.
Constructor & Destructor Documentation
BitReader() [1/2]
pfc::BitReader::BitReader (const uint8_t * ptr, size_t size) inline noexcept
Definition at line 112 of file core.hpp.
BitReader() [2/2]
pfc::BitReader::BitReader (std::span< const uint8_t > buffer) inline explicit noexcept
Definition at line 115 of file core.hpp.
Member Function Documentation
align()
void pfc::BitReader::align () inline noexcept
Definition at line 141 of file core.hpp.
peek()
bool pfc::BitReader::peek () const inline noexcept
Definition at line 118 of file core.hpp.
Referenced by pfc::algorithms::PackedStream< P >::has_more(), pfc::algorithms::PackedStream< P >::next(), pfc::algorithms::PackedStream< P >::skip(), and pfc::algorithms::PackedStream< P >::take().
position()
const uint8_t * pfc::BitReader::position () const inline noexcept
Definition at line 146 of file core.hpp.
read()
bool pfc::BitReader::read () inline noexcept
Definition at line 122 of file core.hpp.
Referenced by read_bits().
read_bits()
uint64_t pfc::BitReader::read_bits (size_t count) inline noexcept
Definition at line 132 of file core.hpp.
References read().
Referenced by pfc::range_decoder::range_decoder().
The documentation for this class was generated from the following file:
pfc/core.hpp