PFC - Prefix-Free Codecs: pfc::PackedVariant< Types > Class Template Reference
pfc::PackedVariant< Types > Class Template Reference
#include <pfc/algebraic.hpp>
Public Types
using value_type = std::variant< typename Types::value_type... >
Public Member Functions
PackedVariant ()=default
template<typename T >
PackedVariant (T &&value)
PackedVariant (const value_type &val)
template<typename Visitor >
auto visit (Visitor &&vis) const
template<typename Visitor >
auto visit (Visitor &&vis)
size_t index () const noexcept
template<typename T >
const T * get_if () const noexcept
template<typename T >
T * get_if () noexcept
value_type value () const
Static Public Member Functions
template<typename Sink >
requires BitSink<Sink>
static void encode (const PackedVariant &var, Sink &sink)
template<typename Source >
requires BitSource<Source>
static PackedVariant decode (Source &source)
Static Public Attributes
static constexpr size_t type_count = sizeof...(Types)
Detailed Description
template<PackedValue... Types>
class pfc::PackedVariant< Types >
Definition at line 78 of file algebraic.hpp.
Member Typedef Documentation
value_type
template<PackedValue... Types> using pfc::PackedVariant< Types >::value_type = std::variant<typename Types::value_type...>
Definition at line 80 of file algebraic.hpp.
Constructor & Destructor Documentation
PackedVariant() [1/3]
template<PackedValue... Types> pfc::PackedVariant< Types >::PackedVariant () default
PackedVariant() [2/3]
template<PackedValue... Types> template<typename T > pfc::PackedVariant< Types >::PackedVariant (T && value) inline explicit
Definition at line 113 of file algebraic.hpp.
PackedVariant() [3/3]
template<PackedValue... Types> pfc::PackedVariant< Types >::PackedVariant (const value_type & val) inline explicit
Definition at line 116 of file algebraic.hpp.
Member Function Documentation
decode()
template<PackedValue... Types> template<typename Source > requires BitSource<Source> static PackedVariant pfc::PackedVariant< Types >::decode (Source & source) inline static
Definition at line 186 of file algebraic.hpp.
Referenced by pfc::PackedList< Element >::decode(), and pfc::PackedTree< Value >::decode().
encode()
template<PackedValue... Types> template<typename Sink > requires BitSink<Sink> static void pfc::PackedVariant< Types >::encode (const PackedVariant< Types > & var, Sink & sink) inline static
Definition at line 174 of file algebraic.hpp.
Referenced by pfc::PackedList< Element >::encode(), and pfc::PackedTree< Value >::encode().
get_if() [1/2]
template<PackedValue... Types> template<typename T > const T * pfc::PackedVariant< Types >::get_if () const inline noexcept
Definition at line 156 of file algebraic.hpp.
get_if() [2/2]
template<PackedValue... Types> template<typename T > T * pfc::PackedVariant< Types >::get_if () inline noexcept
Definition at line 161 of file algebraic.hpp.
index()
template<PackedValue... Types> size_t pfc::PackedVariant< Types >::index () const inline noexcept
Definition at line 150 of file algebraic.hpp.
Referenced by pfc::PackedList< Element >::empty(), and pfc::PackedTree< Value >::empty().
value()
template<PackedValue... Types> value_type pfc::PackedVariant< Types >::value () const inline
Definition at line 166 of file algebraic.hpp.
References pfc::PackedVariant< Types >::visit().
visit() [1/2]
template<PackedValue... Types> template<typename Visitor > auto pfc::PackedVariant< Types >::visit (Visitor && vis) inline
Definition at line 145 of file algebraic.hpp.
visit() [2/2]
template<PackedValue... Types> template<typename Visitor > auto pfc::PackedVariant< Types >::visit (Visitor && vis) const inline
Definition at line 140 of file algebraic.hpp.
Referenced by pfc::PackedVariant< Types >::value().
Member Data Documentation
type_count
template<PackedValue... Types> constexpr size_t pfc::PackedVariant< Types >::type_count = sizeof...(Types) static constexpr
Definition at line 81 of file algebraic.hpp.
The documentation for this class was generated from the following file:
pfc/algebraic.hpp