var hierarchy =
[
    [ "pfc::codecs::Adaptive< SmallCodec, LargeCodec, T >", "structpfc_1_1codecs_1_1Adaptive.html", null ],
    [ "pfc::adaptive_probability_model< Symbols >", "classpfc_1_1adaptive__probability__model.html", null ],
    [ "pfc::codecs::AdaptiveHuffman< Symbol >", "classpfc_1_1codecs_1_1AdaptiveHuffman.html", null ],
    [ "pfc::integrity::Adler32", "classpfc_1_1integrity_1_1Adler32.html", null ],
    [ "pfc::arithmetic_decoder", "classpfc_1_1arithmetic__decoder.html", null ],
    [ "pfc::arithmetic_encoder", "classpfc_1_1arithmetic__encoder.html", null ],
    [ "pfc::ArithmeticCodec< T, Symbols >", "structpfc_1_1ArithmeticCodec.html", null ],
    [ "pfc::async_stream_reader< T, Codec >", "classpfc_1_1async__stream__reader.html", null ],
    [ "pfc::async_stream_writer< T, Codec >", "classpfc_1_1async__stream__writer.html", null ],
    [ "pfc::BasicBitReader< Allocator >", "classpfc_1_1BasicBitReader.html", null ],
    [ "pfc::BasicBitWriter< Allocator >", "classpfc_1_1BasicBitWriter.html", null ],
    [ "pfc::BasicPackedBuffer< Allocator >", "classpfc_1_1BasicPackedBuffer.html", null ],
    [ "pfc::BasicPackedBuffer< std::allocator< uint8_t > >", "classpfc_1_1BasicPackedBuffer.html", null ],
    [ "pfc::BasicPackedVector< T, Codec, Allocator >", "classpfc_1_1BasicPackedVector.html", null ],
    [ "pfc::BitReader", "classpfc_1_1BitReader.html", null ],
    [ "pfc::BitWriter", "classpfc_1_1BitWriter.html", null ],
    [ "pfc::succinct::BlockRankSupport", "classpfc_1_1succinct_1_1BlockRankSupport.html", null ],
    [ "pfc::codecs::Boolean", "structpfc_1_1codecs_1_1Boolean.html", null ],
    [ "pfc::Bottom< T >", "classpfc_1_1Bottom.html", null ],
    [ "pfc::buffer_size_manip", "structpfc_1_1buffer__size__manip.html", null ],
    [ "pfc::codecs::CanonicalHuffman< Symbol >", "classpfc_1_1codecs_1_1CanonicalHuffman.html", null ],
    [ "pfc::integrity::ChecksummedData< Checksum >", "classpfc_1_1integrity_1_1ChecksummedData.html", null ],
    [ "pfc::codec_manip< Codec >", "structpfc_1_1codec__manip.html", null ],
    [ "pfc::algorithms::CodecSelector< T >::CodecInfo< Codec >", "structpfc_1_1algorithms_1_1CodecSelector_1_1CodecInfo.html", null ],
    [ "pfc::algorithms::CodecSelector< T >", "structpfc_1_1algorithms_1_1CodecSelector.html", null ],
    [ "pfc::codecs::Complex< RealCodec, ImagCodec >", "structpfc_1_1codecs_1_1Complex.html", null ],
    [ "pfc::codecs::Complex< RealCodec, ImagCodec >::ComplexNumber", "structpfc_1_1codecs_1_1Complex_1_1ComplexNumber.html", null ],
    [ "pfc::algorithms::CompressionStats", "structpfc_1_1algorithms_1_1CompressionStats.html", null ],
    [ "pfc::context_model< Symbols, Order >", "classpfc_1_1context__model.html", null ],
    [ "pfc::integrity::CRC16", "classpfc_1_1integrity_1_1CRC16.html", null ],
    [ "pfc::integrity::CRC32", "classpfc_1_1integrity_1_1CRC32.html", null ],
    [ "pfc::integrity::CRC64", "classpfc_1_1integrity_1_1CRC64.html", null ],
    [ "pfc::DataValidator", "classpfc_1_1DataValidator.html", null ],
    [ "pfc::algorithms::DeltaCodec< T, Codec >", "classpfc_1_1algorithms_1_1DeltaCodec.html", null ],
    [ "pfc::codecs::EliasDelta", "structpfc_1_1codecs_1_1EliasDelta.html", null ],
    [ "pfc::codecs::EliasGamma", "structpfc_1_1codecs_1_1EliasGamma.html", null ],
    [ "pfc::codecs::EliasOmega", "structpfc_1_1codecs_1_1EliasOmega.html", null ],
    [ "std::error_category", null, [
      [ "pfc::pfc_error_category", "classpfc_1_1pfc__error__category.html", null ]
    ] ],
    [ "pfc::codecs::ExpGolomb< Order >", "structpfc_1_1codecs_1_1ExpGolomb.html", null ],
    [ "pfc::codecs::Fibonacci", "structpfc_1_1codecs_1_1Fibonacci.html", null ],
    [ "pfc::codecs::Fixed< Width >", "structpfc_1_1codecs_1_1Fixed.html", null ],
    [ "pfc::codecs::FixedDecimal< IntegerBits, FractionalBits, IntCodec >", "structpfc_1_1codecs_1_1FixedDecimal.html", null ],
    [ "pfc::codecs::FloatingPoint< MantissaBits, ExponentBits, SignCodec >", "structpfc_1_1codecs_1_1FloatingPoint.html", null ],
    [ "pfc::codecs::Rational< NumeratorCodec, DenominatorCodec >::Fraction", "structpfc_1_1codecs_1_1Rational_1_1Fraction.html", null ],
    [ "pfc::codecs::HuffmanNode< Symbol >", "structpfc_1_1codecs_1_1HuffmanNode.html", null ],
    [ "pfc::codecs::HuffmanNode< uint8_t >", "structpfc_1_1codecs_1_1HuffmanNode.html", null ],
    [ "std::integral_constant", null, [
      [ "std::tuple_size< pfc::succinct::SuccinctBitVector >", "structstd_1_1tuple__size_3_01pfc_1_1succinct_1_1SuccinctBitVector_01_4.html", null ]
    ] ],
    [ "pfc::codecs::Interval< BoundCodec >", "structpfc_1_1codecs_1_1Interval.html", null ],
    [ "pfc::succinct::RoaringBitmap::iterator", "classpfc_1_1succinct_1_1RoaringBitmap_1_1iterator.html", null ],
    [ "pfc::compression::LZ77Compressor< Allocator >", "classpfc_1_1compression_1_1LZ77Compressor.html", null ],
    [ "pfc::compression::LZ77Config", "structpfc_1_1compression_1_1LZ77Config.html", null ],
    [ "pfc::compression::LZ77Decompressor< Allocator >", "classpfc_1_1compression_1_1LZ77Decompressor.html", null ],
    [ "pfc::compression::LZ77Match", "structpfc_1_1compression_1_1LZ77Match.html", null ],
    [ "pfc::compression::LZSS", "classpfc_1_1compression_1_1LZSS.html", null ],
    [ "pfc::OptimalCodec< T >", "structpfc_1_1OptimalCodec.html", null ],
    [ "pfc::Packed< T, Codec >", "classpfc_1_1Packed.html", null ],
    [ "pfc::Packed< double, codecs::Float32 >", "classpfc_1_1Packed.html", null ],
    [ "pfc::PackedAffineTransform< N, Scalar >", "classpfc_1_1PackedAffineTransform.html", null ],
    [ "pfc::PackedBuffer", "classpfc_1_1PackedBuffer.html", null ],
    [ "pfc::PackedContainer< Element >", "classpfc_1_1PackedContainer.html", null ],
    [ "pfc::PackedIterator< Element, Container >", "classpfc_1_1PackedIterator.html", null ],
    [ "pfc::PackedList< Element >", "classpfc_1_1PackedList.html", null ],
    [ "pfc::PackedMatrix< Rows, Cols, Element >", "classpfc_1_1PackedMatrix.html", null ],
    [ "pfc::PackedMatrix< N, N, Packed< double, codecs::Float32 > >", "classpfc_1_1PackedMatrix.html", null ],
    [ "pfc::PackedOptional< T >", "classpfc_1_1PackedOptional.html", null ],
    [ "pfc::PackedPair< First, Second >", "classpfc_1_1PackedPair.html", null ],
    [ "pfc::PackedPoint< N, Coordinate >", "classpfc_1_1PackedPoint.html", null ],
    [ "pfc::PackedProxy< Element, Container >", "classpfc_1_1PackedProxy.html", null ],
    [ "pfc::PackedSharedPtr< T >", "classpfc_1_1PackedSharedPtr.html", null ],
    [ "pfc::algorithms::PackedStream< P >", "classpfc_1_1algorithms_1_1PackedStream.html", null ],
    [ "pfc::PackedTree< Value >", "classpfc_1_1PackedTree.html", null ],
    [ "pfc::PackedTuple< Types >", "classpfc_1_1PackedTuple.html", null ],
    [ "pfc::PackedVariant< Types >", "classpfc_1_1PackedVariant.html", null ],
    [ "pfc::PackedVariant< Element >", "classpfc_1_1PackedVariant.html", null ],
    [ "pfc::PackedVariant< Value >", "classpfc_1_1PackedVariant.html", null ],
    [ "pfc::PackedVec< N, Component >", "classpfc_1_1PackedVec.html", null ],
    [ "pfc::PackedVec< N, Packed< double, codecs::Float32 > >", "classpfc_1_1PackedVec.html", null ],
    [ "pfc::PackedVector< Element, LengthCodec >", "classpfc_1_1PackedVector.html", null ],
    [ "pfc::algorithms::ParallelEncoder< T, Codec >", "structpfc_1_1algorithms_1_1ParallelEncoder.html", null ],
    [ "pfc::codecs::Interval< BoundCodec >::Range", "structpfc_1_1codecs_1_1Interval_1_1Range.html", null ],
    [ "pfc::range_decoder", "classpfc_1_1range__decoder.html", null ],
    [ "pfc::range_encoder", "classpfc_1_1range__encoder.html", null ],
    [ "pfc::RangeCodec< T, Symbols >", "structpfc_1_1RangeCodec.html", null ],
    [ "pfc::codecs::Rational< NumeratorCodec, DenominatorCodec >", "structpfc_1_1codecs_1_1Rational.html", null ],
    [ "pfc::result< T >", "classpfc_1_1result.html", null ],
    [ "pfc::result< void >", "classpfc_1_1result_3_01void_01_4.html", null ],
    [ "pfc::codecs::Rice< K >", "structpfc_1_1codecs_1_1Rice.html", null ],
    [ "pfc::succinct::RoaringBitmap", "classpfc_1_1succinct_1_1RoaringBitmap.html", null ],
    [ "pfc::algorithms::RunLengthCodec< T, ValueCodec, CountCodec >", "classpfc_1_1algorithms_1_1RunLengthCodec.html", null ],
    [ "pfc::SafeBitReader< Allocator >", "classpfc_1_1SafeBitReader.html", null ],
    [ "pfc::SafeBitWriter< Allocator >", "classpfc_1_1SafeBitWriter.html", null ],
    [ "pfc::codecs::Scientific< MantissaCodec, ExponentCodec >", "structpfc_1_1codecs_1_1Scientific.html", null ],
    [ "pfc::codecs::Scientific< MantissaCodec, ExponentCodec >::SciNumber", "structpfc_1_1codecs_1_1Scientific_1_1SciNumber.html", null ],
    [ "pfc::codecs::Signed< UnsignedCodec >", "structpfc_1_1codecs_1_1Signed.html", null ],
    [ "pfc::static_probability_model< Symbols >", "classpfc_1_1static__probability__model.html", null ],
    [ "pfc::codecs::StaticHuffman< Symbol, Allocator >", "classpfc_1_1codecs_1_1StaticHuffman.html", null ],
    [ "pfc::succinct::RoaringBitmap::Stats", "structpfc_1_1succinct_1_1RoaringBitmap_1_1Stats.html", null ],
    [ "pfc::stream_bit_reader", "classpfc_1_1stream__bit__reader.html", null ],
    [ "pfc::stream_bit_writer", "classpfc_1_1stream__bit__writer.html", null ],
    [ "std::streambuf", null, [
      [ "pfc::bit_streambuf", "classpfc_1_1bit__streambuf.html", [
        [ "pfc::input_bit_streambuf", "classpfc_1_1input__bit__streambuf.html", null ],
        [ "pfc::output_bit_streambuf", "classpfc_1_1output__bit__streambuf.html", null ]
      ] ]
    ] ],
    [ "pfc::succinct::SuccinctBitVector", "classpfc_1_1succinct_1_1SuccinctBitVector.html", null ],
    [ "true_type", null, [
      [ "std::is_error_code_enum< pfc::pfc_error >", "structstd_1_1is__error__code__enum_3_01pfc_1_1pfc__error_01_4.html", null ]
    ] ],
    [ "pfc::TypeErasedPackedContainer", "classpfc_1_1TypeErasedPackedContainer.html", null ],
    [ "pfc::codecs::Unary", "structpfc_1_1codecs_1_1Unary.html", null ],
    [ "pfc::Unit", "structpfc_1_1Unit.html", null ],
    [ "pfc::codecs::VByte", "structpfc_1_1codecs_1_1VByte.html", null ],
    [ "pfc::WriterTransaction< Writer >", "classpfc_1_1WriterTransaction.html", null ],
    [ "pfc::integrity::XXHash32", "classpfc_1_1integrity_1_1XXHash32.html", null ]
];