PFC - Prefix-Free Codecs: pfc Namespace Reference
pfc Namespace Reference
Namespaces
namespace algorithms
namespace codecs
namespace compression
namespace integrity
namespace pmr
namespace succinct
Classes
class adaptive_probability_model
class arithmetic_decoder
class arithmetic_encoder
struct ArithmeticCodec
class async_stream_reader
class async_stream_writer
class BasicBitReader
class BasicBitWriter
class BasicPackedBuffer
class BasicPackedVector
class bit_streambuf
class BitReader
class BitWriter
class Bottom
struct buffer_size_manip
struct codec_manip
class context_model
class DataValidator
class input_bit_streambuf
struct OptimalCodec
class output_bit_streambuf
class Packed
class PackedAffineTransform
class PackedBuffer
class PackedContainer
class PackedIterator
class PackedList
class PackedMatrix
class PackedOptional
class PackedPair
class PackedPoint
class PackedProxy
class PackedSharedPtr
class PackedTree
class PackedTuple
class PackedVariant
class PackedVec
class PackedVector
class pfc_error_category
class range_decoder
class range_encoder
struct RangeCodec
class result
class result< void >
class SafeBitReader
class SafeBitWriter
class static_probability_model
class stream_bit_reader
class stream_bit_writer
class TypeErasedPackedContainer
struct Unit
class WriterTransaction
Concepts
concept ProbabilityModel
concept Regular
concept TotallyOrdered
concept Additive
concept VectorSpace
concept BitSink
concept BitSource
concept Encoder
concept Decoder
concept Codec
concept PackedValue
Typedefs
template<PackedValue Element>
using PackedListNode = PackedVariant< Unit, PackedPair< Element, PackedSharedPtr< PackedList< Element > > > >
template<PackedValue Value>
using PackedTreeNode = PackedVariant< Unit, PackedTuple< Value, PackedSharedPtr< PackedTree< Value > >, PackedSharedPtr< PackedTree< Value > > > >
template<PackedValue Left, PackedValue Right>
using PackedEither = PackedVariant< Left, Right >
template<PackedValue T>
using PackedMaybe = PackedVariant< Unit, T >
template<PackedValue T, PackedValue E = Packed<std::string, codecs::EliasGamma>>
using PackedResult = PackedEither< E, T >
template<typename T , typename Codec >
using AllocPackedVector = BasicPackedVector< T, Codec, std::allocator< uint8_t > >
template<typename Coord = PackedI32<>>
using PackedPoint2D = PackedPoint< 2, Coord >
template<typename Coord = PackedI32<>>
using PackedPoint3D = PackedPoint< 3, Coord >
using PackedVec2 = PackedVec< 2 >
using PackedVec3 = PackedVec< 3 >
using PackedVec4 = PackedVec< 4 >
using PackedMatrix2x2 = PackedMatrix< 2, 2 >
using PackedMatrix3x3 = PackedMatrix< 3, 3 >
using PackedMatrix4x4 = PackedMatrix< 4, 4 >
using PackedTransform2D = PackedAffineTransform< 2 >
using PackedTransform3D = PackedAffineTransform< 3 >
template<typename T >
using expected = result< T >
template<typename Codec = codecs::EliasGamma>
using PackedU32 = Packed< uint32_t, Codec >
template<typename Codec = codecs::EliasGamma>
using PackedU64 = Packed< uint64_t, Codec >
template<typename Codec = codecs::SignedGamma>
using PackedI32 = Packed< int32_t, Codec >
template<typename Codec = codecs::SignedGamma>
using PackedI64 = Packed< int64_t, Codec >
using PackedBool = Packed< bool, codecs::Boolean >
template<size_t K>
using Rice = codecs::Rice< K >
template<size_t Width>
using Fixed = codecs::Fixed< Width >
using U32 = PackedU32< EliasGamma >
using U64 = PackedU64< EliasGamma >
using I32 = PackedI32< SignedGamma >
using I64 = PackedI64< SignedGamma >
using Bool = PackedBool
Enumerations
enum class pfc_error {
success = 0 , buffer_overflow , buffer_underflow , invalid_input ,
corrupted_data , unsupported_codec , allocation_failure , io_error ,
checksum_mismatch , compression_error , decompression_error , eof_reached ,
incomplete_data , invalid_header , invalid_parameter
}
enum class DataDistribution {
Uniform , Geometric , PowerLaw , Sparse ,
Unknown
}
Functions
template<typename InputIt , typename OutputIt >
result< std::size_t > arithmetic_compress (InputIt first, InputIt last, OutputIt output)
template<typename InputIt , typename OutputIt >
result< std::size_t > arithmetic_decompress (InputIt first, InputIt last, OutputIt output, std::size_t count)
template<typename InputIt , typename OutputIt >
result< std::size_t > range_compress (InputIt first, InputIt last, OutputIt output)
template<typename InputIt , typename OutputIt >
result< std::size_t > range_decompress (InputIt first, InputIt last, OutputIt output, std::size_t count)
template<std::unsigned_integral T>
constexpr int count_leading_zeros (T x) noexcept
template<std::unsigned_integral T>
constexpr int msb_position (T x) noexcept
const pfc_error_category & get_pfc_error_category ()
std::error_code make_error_code (pfc_error e)
template<typename T , typename Codec = EliasGamma>
std::vector< uint8_t > compress (const std::vector< T > &data)
template<typename T , typename Codec = EliasGamma>
std::vector< T > decompress (const std::vector< uint8_t > &compressed)
template<typename T >
double calculate_entropy (const std::vector< T > &data)
template<typename T >
const char * suggest_codec (const std::vector< T > &sample)
template<PackedValue Element>
void sort (PackedContainer< Element > &container)
template<typename Codec >
void sort (PackedContainer< Packed< uint32_t, Codec > > &container)
template<typename Codec >
codec_manip< Codec > with_codec ()
buffer_size_manip buffer_size (std::size_t size)
template<typename T , typename Codec = codecs::EliasGamma, typename Allocator = std::allocator<T>>
result< std::size_t > write_compressed_file (const std::string &filename, const std::vector< T, Allocator > &data, std::ios::openmode mode=std::ios::binary)
template<typename T , typename Codec = codecs::EliasGamma, typename Allocator = std::allocator<T>>
result< std::vector< T, Allocator > > read_compressed_file (const std::string &filename, std::ios::openmode mode=std::ios::binary)
template<typename T , typename Codec = codecs::EliasGamma>
result< std::string > compress_to_string (const std::vector< T > &data)
template<typename T , typename Codec = codecs::EliasGamma>
result< std::vector< T > > decompress_from_string (const std::string &compressed)
template<typename T , typename Codec >
std::ostream & operator<< (std::ostream &os, const Packed< T, Codec > &packed)
template<typename T , typename Codec >
std::istream & operator>> (std::istream &is, Packed< T, Codec > &packed)
Variables
constexpr int VERSION_MAJOR = 1
constexpr int VERSION_MINOR = 0
constexpr int VERSION_PATCH = 0
Typedef Documentation
AllocPackedVector
template<typename T , typename Codec > using pfc::AllocPackedVector = typedef BasicPackedVector<T, Codec, std::allocator<uint8_t> >
Definition at line 243 of file allocator_support.hpp.
Bool
using pfc::Bool = typedef PackedBool
Definition at line 61 of file pfc.hpp.
expected
template<typename T > using pfc::expected = typedef result<T>
Definition at line 148 of file error_handling.hpp.
Fixed
template<size_t Width> using pfc::Fixed = typedef codecs::Fixed<Width>
Definition at line 54 of file pfc.hpp.
I32
using pfc::I32 = typedef PackedI32<SignedGamma>
Definition at line 59 of file pfc.hpp.
I64
using pfc::I64 = typedef PackedI64<SignedGamma>
Definition at line 60 of file pfc.hpp.
PackedBool
using pfc::PackedBool = typedef Packed<bool, codecs::Boolean>
Definition at line 83 of file packed.hpp.
PackedEither
template<PackedValue Left, PackedValue Right> using pfc::PackedEither = typedef PackedVariant<Left, Right>
Definition at line 495 of file algebraic.hpp.
PackedI32
template<typename Codec = codecs::SignedGamma> using pfc::PackedI32 = typedef Packed<int32_t, Codec>
Definition at line 78 of file packed.hpp.
PackedI64
template<typename Codec = codecs::SignedGamma> using pfc::PackedI64 = typedef Packed<int64_t, Codec>
Definition at line 81 of file packed.hpp.
PackedListNode
template<PackedValue Element> using pfc::PackedListNode = typedef PackedVariant< Unit, PackedPair<Element, PackedSharedPtr<PackedList<Element> >> >
Definition at line 262 of file algebraic.hpp.
PackedMatrix2x2
using pfc::PackedMatrix2x2 = typedef PackedMatrix<2, 2>
Definition at line 497 of file coordinates.hpp.
PackedMatrix3x3
using pfc::PackedMatrix3x3 = typedef PackedMatrix<3, 3>
Definition at line 498 of file coordinates.hpp.
PackedMatrix4x4
using pfc::PackedMatrix4x4 = typedef PackedMatrix<4, 4>
Definition at line 499 of file coordinates.hpp.
PackedMaybe
template<PackedValue T> using pfc::PackedMaybe = typedef PackedVariant<Unit, T>
Definition at line 499 of file algebraic.hpp.
PackedPoint2D
template<typename Coord = PackedI32<>> using pfc::PackedPoint2D = typedef PackedPoint<2, Coord>
Definition at line 116 of file coordinates.hpp.
PackedPoint3D
template<typename Coord = PackedI32<>> using pfc::PackedPoint3D = typedef PackedPoint<3, Coord>
Definition at line 119 of file coordinates.hpp.
PackedResult
template<PackedValue T, PackedValue E = Packed<std::string, codecs::EliasGamma>> using pfc::PackedResult = typedef PackedEither<E, T>
Definition at line 503 of file algebraic.hpp.
PackedTransform2D
using pfc::PackedTransform2D = typedef PackedAffineTransform<2>
Definition at line 583 of file coordinates.hpp.
PackedTransform3D
using pfc::PackedTransform3D = typedef PackedAffineTransform<3>
Definition at line 584 of file coordinates.hpp.
PackedTreeNode
template<PackedValue Value> using pfc::PackedTreeNode = typedef PackedVariant< Unit, PackedTuple<Value, PackedSharedPtr<PackedTree<Value> >, PackedSharedPtr<PackedTree<Value> >> >
Definition at line 391 of file algebraic.hpp.
PackedU32
template<typename Codec = codecs::EliasGamma> using pfc::PackedU32 = typedef Packed<uint32_t, Codec>
Definition at line 72 of file packed.hpp.
PackedU64
template<typename Codec = codecs::EliasGamma> using pfc::PackedU64 = typedef Packed<uint64_t, Codec>
Definition at line 75 of file packed.hpp.
PackedVec2
using pfc::PackedVec2 = typedef PackedVec<2>
Definition at line 307 of file coordinates.hpp.
PackedVec3
using pfc::PackedVec3 = typedef PackedVec<3>
Definition at line 308 of file coordinates.hpp.
PackedVec4
using pfc::PackedVec4 = typedef PackedVec<4>
Definition at line 309 of file coordinates.hpp.
Rice
template<size_t K> using pfc::Rice = typedef codecs::Rice<K>
Definition at line 51 of file pfc.hpp.
U32
using pfc::U32 = typedef PackedU32<EliasGamma>
Definition at line 57 of file pfc.hpp.
U64
using pfc::U64 = typedef PackedU64<EliasGamma>
Definition at line 58 of file pfc.hpp.
Enumeration Type Documentation
DataDistribution
enum class pfc::DataDistribution strong
Enumerator
Uniform
Geometric
PowerLaw
Sparse
Unknown
Definition at line 118 of file pfc.hpp.
pfc_error
enum class pfc::pfc_error strong
Enumerator
success
buffer_overflow
buffer_underflow
invalid_input
corrupted_data
unsupported_codec
allocation_failure
io_error
checksum_mismatch
compression_error
decompression_error
eof_reached
incomplete_data
invalid_header
invalid_parameter
Definition at line 15 of file error_handling.hpp.
Function Documentation
arithmetic_compress()
template<typename InputIt , typename OutputIt > result< std::size_t > pfc::arithmetic_compress (InputIt first, InputIt last, OutputIt output)
Definition at line 528 of file arithmetic_coding.hpp.
References pfc::BitWriter::align(), pfc::BitWriter::bytes_written(), compression_error, pfc::arithmetic_encoder::encode_symbol(), pfc::arithmetic_encoder::finish(), and make_error_code().
arithmetic_decompress()
template<typename InputIt , typename OutputIt > result< std::size_t > pfc::arithmetic_decompress (InputIt first, InputIt last, OutputIt output, std::size_t count)
Definition at line 556 of file arithmetic_coding.hpp.
References pfc::arithmetic_decoder::decode_symbol(), decompression_error, and make_error_code().
buffer_size()
buffer_size_manip pfc::buffer_size (std::size_t size) inline
Definition at line 293 of file stream_io.hpp.
calculate_entropy()
template<typename T > double pfc::calculate_entropy (const std::vector< T > & data)
Definition at line 150 of file pfc.hpp.
compress()
template<typename T , typename Codec = EliasGamma> std::vector< uint8_t > pfc::compress (const std::vector< T > & data)
Definition at line 69 of file pfc.hpp.
References pfc::codecs::EliasGamma::encode().
compress_to_string()
template<typename T , typename Codec = codecs::EliasGamma> result< std::string > pfc::compress_to_string (const std::vector< T > & data)
Definition at line 374 of file stream_io.hpp.
References compression_error, pfc::stream_bit_writer::flush(), pfc::stream_bit_writer::good(), and make_error_code().
count_leading_zeros()
template<std::unsigned_integral T> constexpr int pfc::count_leading_zeros (T x) constexpr noexcept
Definition at line 157 of file core.hpp.
Referenced by msb_position().
decompress()
template<typename T , typename Codec = EliasGamma> std::vector< T > pfc::decompress (const std::vector< uint8_t > & compressed)
Definition at line 95 of file pfc.hpp.
decompress_from_string()
template<typename T , typename Codec = codecs::EliasGamma> result< std::vector< T > > pfc::decompress_from_string (const std::string & compressed)
Definition at line 399 of file stream_io.hpp.
References pfc::stream_bit_reader::bad(), corrupted_data, decompression_error, pfc::stream_bit_reader::fail(), and make_error_code().
get_pfc_error_category()
const pfc_error_category & pfc::get_pfc_error_category () inline
Definition at line 79 of file error_handling.hpp.
Referenced by make_error_code().
make_error_code()
std::error_code pfc::make_error_code (pfc_error e) inline
Definition at line 85 of file error_handling.hpp.
References get_pfc_error_category().
Referenced by pfc::SafeBitWriter< Allocator >::align(), arithmetic_compress(), arithmetic_decompress(), compress_to_string(), pfc::compression::LZ77Match::decode(), pfc::codecs::StaticHuffman< Symbol, Allocator >::decode_symbol(), pfc::compression::LZ77Decompressor< Allocator >::decompress(), pfc::compression::LZ77Decompressor< Allocator >::decompress_from_bits(), decompress_from_string(), pfc::codecs::StaticHuffman< Symbol, Allocator >::encode_symbol(), pfc::codecs::CanonicalHuffman< Symbol >::encode_symbol(), pfc::codecs::StaticHuffman< Symbol, Allocator >::from_frequencies(), pfc::codecs::CanonicalHuffman< Symbol >::from_frequencies(), range_compress(), range_decompress(), pfc::SafeBitReader< Allocator >::read_bit(), pfc::SafeBitReader< Allocator >::read_bits(), read_compressed_file(), pfc::codecs::StaticHuffman< Symbol, Allocator >::read_header(), pfc::DataValidator::validate_codec_id(), pfc::DataValidator::validate_header(), pfc::SafeBitWriter< Allocator >::write_bit(), and write_compressed_file().
msb_position()
template<std::unsigned_integral T> constexpr int pfc::msb_position (T x) constexpr noexcept
Definition at line 170 of file core.hpp.
References count_leading_zeros().
Referenced by pfc::codecs::EliasDelta::encode(), pfc::codecs::ExpGolomb< Order >::encode(), pfc::codecs::EliasOmega::encode(), and pfc::codecs::EliasGamma::encode().
operator<<()
template<typename T , typename Codec > std::ostream & pfc::operator<< (std::ostream & os, const Packed< T, Codec > & packed)
Definition at line 430 of file stream_io.hpp.
References pfc::stream_bit_writer::flush(), and pfc::Packed< T, Codec >::value().
operator>>()
template<typename T , typename Codec > std::istream & pfc::operator>> (std::istream & is, Packed< T, Codec > & packed)
Definition at line 439 of file stream_io.hpp.
range_compress()
template<typename InputIt , typename OutputIt > result< std::size_t > pfc::range_compress (InputIt first, InputIt last, OutputIt output)
Definition at line 577 of file arithmetic_coding.hpp.
References pfc::BitWriter::align(), pfc::BitWriter::bytes_written(), compression_error, pfc::range_encoder::encode_symbol(), pfc::range_encoder::finish(), and make_error_code().
range_decompress()
template<typename InputIt , typename OutputIt > result< std::size_t > pfc::range_decompress (InputIt first, InputIt last, OutputIt output, std::size_t count)
Definition at line 602 of file arithmetic_coding.hpp.
References pfc::range_decoder::decode_symbol(), decompression_error, and make_error_code().
read_compressed_file()
template<typename T , typename Codec = codecs::EliasGamma, typename Allocator = std::allocator<T>> result< std::vector< T, Allocator > > pfc::read_compressed_file (const std::string & filename, std::ios::openmode mode = std::ios::binary)
Definition at line 337 of file stream_io.hpp.
References pfc::stream_bit_reader::bad(), corrupted_data, decompression_error, pfc::stream_bit_reader::fail(), io_error, and make_error_code().
sort() [1/2]
template<PackedValue Element> void pfc::sort (PackedContainer< Element > & container)
Definition at line 555 of file stl_integration.hpp.
References pfc::PackedContainer< Element >::clear(), pfc::PackedContainer< Element >::push_back(), and pfc::PackedContainer< Element >::size().
sort() [2/2]
template<typename Codec > void pfc::sort (PackedContainer< Packed< uint32_t, Codec > > & container)
Definition at line 574 of file stl_integration.hpp.
suggest_codec()
template<typename T > const char * pfc::suggest_codec (const std::vector< T > & sample)
Definition at line 173 of file pfc.hpp.
with_codec()
template<typename Codec > codec_manip< Codec > pfc::with_codec ()
Definition at line 283 of file stream_io.hpp.
write_compressed_file()
template<typename T , typename Codec = codecs::EliasGamma, typename Allocator = std::allocator<T>> result< std::size_t > pfc::write_compressed_file (const std::string & filename, const std::vector< T, Allocator > & data, std::ios::openmode mode = std::ios::binary)
Definition at line 303 of file stream_io.hpp.
References pfc::stream_bit_writer::bytes_written(), compression_error, pfc::stream_bit_writer::flush(), pfc::stream_bit_writer::good(), io_error, and make_error_code().
Variable Documentation
VERSION_MAJOR
constexpr int pfc::VERSION_MAJOR = 1 constexpr
Definition at line 37 of file pfc.hpp.
VERSION_MINOR
constexpr int pfc::VERSION_MINOR = 0 constexpr
Definition at line 38 of file pfc.hpp.
VERSION_PATCH
constexpr int pfc::VERSION_PATCH = 0 constexpr
Definition at line 39 of file pfc.hpp.