PFC - Prefix-Free Codecs: pfc::algorithms Namespace Reference
pfc::algorithms Namespace Reference
Classes
struct CodecSelector
struct CompressionStats
class DeltaCodec
class PackedStream
struct ParallelEncoder
class RunLengthCodec
Functions
template<std::ranges::input_range Range, typename Codec >
requires std::convertible_to<std::ranges::range_value_t<Range>, typename Codec::value_type>
void encode_range (const Range &range, auto &sink) BitSink< decltype(sink)>
template<typename T , typename Codec , typename Source >
requires BitSource<Source>
std::vector< T > decode_n (Source &source, size_t count)
template<typename T , typename Codec , typename Source >
requires BitSource<Source>
std::vector< T > decode_all (Source &source)
template<PackedValue Input, PackedValue Output, typename UnaryOp >
Output transform_packed (const Input &input, UnaryOp op)
template<std::ranges::input_range Range, PackedValue Output, typename UnaryOp >
requires PackedValue<std::ranges::range_value_t<Range>>
auto transform_packed_range (const Range &range, UnaryOp op)
template<typename T , typename Codec >
CompressionStats analyze_compression (const std::vector< T > &values)
template<PackedValue Input, typename F >
auto packed_transform (const PackedContainer< Input > &input, F &&f)
template<PackedValue Element, typename T , typename BinaryOp >
T packed_accumulate (const PackedContainer< Element > &container, T init, BinaryOp &&op)
template<PackedValue Element, typename Predicate >
std::optional< size_t > packed_find_if (const PackedContainer< Element > &container, Predicate &&pred)
template<typename ExecPolicy , PackedValue Input, typename F >
auto packed_transform_par (ExecPolicy &&policy, const PackedContainer< Input > &input, F &&f)
template<PackedValue Element>
PackedContainer< Element > packed_merge (const PackedContainer< Element > &a, const PackedContainer< Element > &b)
Function Documentation
analyze_compression()
template<typename T , typename Codec > CompressionStats pfc::algorithms::analyze_compression (const std::vector< T > & values)
Definition at line 85 of file algorithms.hpp.
References pfc::BitWriter::align(), pfc::algorithms::CompressionStats::original_bits, and pfc::BitWriter::position().
decode_all()
template<typename T , typename Codec , typename Source > requires BitSource<Source> std::vector< T > pfc::algorithms::decode_all (Source & source)
Definition at line 41 of file algorithms.hpp.
decode_n()
template<typename T , typename Codec , typename Source > requires BitSource<Source> std::vector< T > pfc::algorithms::decode_n (Source & source, size_t count)
Definition at line 30 of file algorithms.hpp.
encode_range()
template<std::ranges::input_range Range, typename Codec > requires std::convertible_to<std::ranges::range_value_t<Range>, typename Codec::value_type> void pfc::algorithms::encode_range (const Range & range, auto & sink)
Definition at line 22 of file algorithms.hpp.
packed_accumulate()
template<PackedValue Element, typename T , typename BinaryOp > T pfc::algorithms::packed_accumulate (const PackedContainer< Element > & container, T init, BinaryOp && op)
Definition at line 459 of file stl_integration.hpp.
References pfc::PackedContainer< Element >::size().
packed_find_if()
template<PackedValue Element, typename Predicate > std::optional< size_t > pfc::algorithms::packed_find_if (const PackedContainer< Element > & container, Predicate && pred)
Definition at line 470 of file stl_integration.hpp.
References pfc::PackedContainer< Element >::size().
packed_merge()
template<PackedValue Element> PackedContainer< Element > pfc::algorithms::packed_merge (const PackedContainer< Element > & a, const PackedContainer< Element > & b)
Definition at line 508 of file stl_integration.hpp.
References pfc::PackedContainer< Element >::raw_data(), and pfc::PackedContainer< Element >::size().
packed_transform()
template<PackedValue Input, typename F > auto pfc::algorithms::packed_transform (const PackedContainer< Input > & input, F && f)
Definition at line 443 of file stl_integration.hpp.
References pfc::PackedContainer< Element >::size().
packed_transform_par()
template<typename ExecPolicy , PackedValue Input, typename F > auto pfc::algorithms::packed_transform_par (ExecPolicy && policy, const PackedContainer< Input > & input, F && f)
Definition at line 482 of file stl_integration.hpp.
References pfc::PackedContainer< Element >::begin(), pfc::PackedContainer< Element >::end(), and pfc::PackedContainer< Element >::size().
transform_packed()
template<PackedValue Input, PackedValue Output, typename UnaryOp > Output pfc::algorithms::transform_packed (const Input & input, UnaryOp op)
Definition at line 55 of file algorithms.hpp.
transform_packed_range()
template<std::ranges::input_range Range, PackedValue Output, typename UnaryOp > requires PackedValue<std::ranges::range_value_t<Range>> auto pfc::algorithms::transform_packed_range (const Range & range, UnaryOp op)
Definition at line 62 of file algorithms.hpp.