PFC - Prefix-Free Codecs: pfc::RangeCodec< T, Symbols > Struct Template Reference
pfc::RangeCodec< T, Symbols > Struct Template Reference
#include <pfc/arithmetic_coding.hpp>
Public Types
using value_type = T
Static Public Member Functions
template<BitSink Sink>
static void encode (const T &value, Sink &sink)
template<BitSource Source>
static T decode (Source &source)
Detailed Description
template<typename T, std::size_t Symbols = 256>
struct pfc::RangeCodec< T, Symbols >
Definition at line 660 of file arithmetic_coding.hpp.
Member Typedef Documentation
value_type
template<typename T , std::size_t Symbols = 256> using pfc::RangeCodec< T, Symbols >::value_type = T
Definition at line 661 of file arithmetic_coding.hpp.
Member Function Documentation
decode()
template<typename T , std::size_t Symbols = 256> template<BitSource Source> static T pfc::RangeCodec< T, Symbols >::decode (Source & source) inline static
Definition at line 677 of file arithmetic_coding.hpp.
References pfc::range_decoder::decode_symbol().
encode()
template<typename T , std::size_t Symbols = 256> template<BitSink Sink> static void pfc::RangeCodec< T, Symbols >::encode (const T & value, Sink & sink) inline static
Definition at line 664 of file arithmetic_coding.hpp.
References pfc::range_encoder::encode_symbol(), and pfc::range_encoder::finish().
The documentation for this struct was generated from the following file:
pfc/arithmetic_coding.hpp