PFC - Prefix-Free Codecs: pfc::codecs::FixedDecimal< IntegerBits, FractionalBits, IntCodec > Struct Template Reference
pfc::codecs::FixedDecimal< IntegerBits, FractionalBits, IntCodec > Struct Template Reference
#include <pfc/numeric_codecs.hpp>
Static Public Member Functions
static void encode (double value, auto &sink)
static double decode (auto &source)
Static Public Attributes
static constexpr double scale = std::pow(10.0, FractionalBits)
Detailed Description
template<size_t IntegerBits, size_t FractionalBits, typename IntCodec = EliasGamma>
struct pfc::codecs::FixedDecimal< IntegerBits, FractionalBits, IntCodec >
Definition at line 141 of file numeric_codecs.hpp.
Member Function Documentation
decode()
template<size_t IntegerBits, size_t FractionalBits, typename IntCodec = EliasGamma> static double pfc::codecs::FixedDecimal< IntegerBits, FractionalBits, IntCodec >::decode (auto & source) inline static
Definition at line 155 of file numeric_codecs.hpp.
References pfc::codecs::FixedDecimal< IntegerBits, FractionalBits, IntCodec >::scale.
encode()
template<size_t IntegerBits, size_t FractionalBits, typename IntCodec = EliasGamma> static void pfc::codecs::FixedDecimal< IntegerBits, FractionalBits, IntCodec >::encode (double value, auto & sink) inline static
Definition at line 147 of file numeric_codecs.hpp.
References pfc::codecs::Signed< UnsignedCodec >::encode(), and pfc::codecs::FixedDecimal< IntegerBits, FractionalBits, IntCodec >::scale.
Member Data Documentation
scale
template<size_t IntegerBits, size_t FractionalBits, typename IntCodec = EliasGamma> constexpr double pfc::codecs::FixedDecimal< IntegerBits, FractionalBits, IntCodec >::scale = std::pow(10.0, FractionalBits) static constexpr
Definition at line 145 of file numeric_codecs.hpp.
Referenced by pfc::codecs::FixedDecimal< IntegerBits, FractionalBits, IntCodec >::decode(), and pfc::codecs::FixedDecimal< IntegerBits, FractionalBits, IntCodec >::encode().
The documentation for this struct was generated from the following file:
pfc/numeric_codecs.hpp