PFC - Prefix-Free Codecs: pfc::codecs::Rational< NumeratorCodec, DenominatorCodec > Struct Template Reference
pfc::codecs::Rational< NumeratorCodec, DenominatorCodec > Struct Template Reference
#include <pfc/numeric_codecs.hpp>
Classes
struct Fraction
Static Public Member Functions
static void encode (double value, auto &sink)
static double decode (auto &source)
static void encode_fraction (const Fraction &frac, auto &sink)
static Fraction decode_fraction (auto &source)
Detailed Description
template<typename NumeratorCodec = SignedGamma, typename DenominatorCodec = EliasGamma>
struct pfc::codecs::Rational< NumeratorCodec, DenominatorCodec >
Definition at line 171 of file numeric_codecs.hpp.
Member Function Documentation
decode()
template<typename NumeratorCodec = SignedGamma, typename DenominatorCodec = EliasGamma> static double pfc::codecs::Rational< NumeratorCodec, DenominatorCodec >::decode (auto & source) inline static
Definition at line 240 of file numeric_codecs.hpp.
decode_fraction()
template<typename NumeratorCodec = SignedGamma, typename DenominatorCodec = EliasGamma> static Fraction pfc::codecs::Rational< NumeratorCodec, DenominatorCodec >::decode_fraction (auto & source) inline static
Definition at line 257 of file numeric_codecs.hpp.
encode()
template<typename NumeratorCodec = SignedGamma, typename DenominatorCodec = EliasGamma> static void pfc::codecs::Rational< NumeratorCodec, DenominatorCodec >::encode (double value, auto & sink) inline static
Definition at line 232 of file numeric_codecs.hpp.
References pfc::codecs::Rational< NumeratorCodec, DenominatorCodec >::Fraction::denominator, pfc::codecs::Rational< NumeratorCodec, DenominatorCodec >::Fraction::from_double(), pfc::codecs::Rational< NumeratorCodec, DenominatorCodec >::Fraction::numerator, and pfc::codecs::Rational< NumeratorCodec, DenominatorCodec >::Fraction::simplify().
encode_fraction()
template<typename NumeratorCodec = SignedGamma, typename DenominatorCodec = EliasGamma> static void pfc::codecs::Rational< NumeratorCodec, DenominatorCodec >::encode_fraction (const Fraction & frac, auto & sink) inline static
Definition at line 249 of file numeric_codecs.hpp.
References pfc::codecs::Rational< NumeratorCodec, DenominatorCodec >::Fraction::denominator, pfc::codecs::Rational< NumeratorCodec, DenominatorCodec >::Fraction::numerator, and pfc::codecs::Rational< NumeratorCodec, DenominatorCodec >::Fraction::simplify().
The documentation for this struct was generated from the following file:
pfc/numeric_codecs.hpp