PFC - Prefix-Free Codecs: pfc::compression::LZ77Match Struct Reference
pfc::compression::LZ77Match Struct Reference
#include <pfc/lz77.hpp>
Public Member Functions
bool is_literal () const
template<typename BitSink >
result< void > encode (BitSink &sink) const
Static Public Member Functions
template<typename BitSource >
static result< LZ77Match > decode (BitSource &source)
Public Attributes
uint16_t distance
uint16_t length
uint8_t literal
Detailed Description
Definition at line 34 of file lz77.hpp.
Member Function Documentation
decode()
template<typename BitSource > static result< LZ77Match > pfc::compression::LZ77Match::decode (BitSource & source) inline static
Definition at line 67 of file lz77.hpp.
References distance, pfc::eof_reached, pfc::incomplete_data, and pfc::make_error_code().
Referenced by pfc::compression::LZ77Decompressor< Allocator >::decompress_from_bits().
encode()
template<typename BitSink > result< void > pfc::compression::LZ77Match::encode (BitSink & sink) const inline
Definition at line 43 of file lz77.hpp.
References distance, is_literal(), length, and literal.
is_literal()
bool pfc::compression::LZ77Match::is_literal () const inline
Definition at line 39 of file lz77.hpp.
References distance.
Referenced by pfc::compression::LZ77Decompressor< Allocator >::decompress(), and encode().
Member Data Documentation
distance
uint16_t pfc::compression::LZ77Match::distance
Definition at line 35 of file lz77.hpp.
Referenced by decode(), pfc::compression::LZ77Decompressor< Allocator >::decompress(), encode(), and is_literal().
length
uint16_t pfc::compression::LZ77Match::length
Definition at line 36 of file lz77.hpp.
Referenced by pfc::compression::LZ77Decompressor< Allocator >::decompress(), and encode().
literal
uint8_t pfc::compression::LZ77Match::literal
Definition at line 37 of file lz77.hpp.
Referenced by pfc::compression::LZ77Decompressor< Allocator >::decompress(), and encode().
The documentation for this struct was generated from the following file:
pfc/lz77.hpp